INSERT INTO Musicians (name) VALUES("Frainc");
INSERT INTO Musicians (name) VALUES("Johnny Mc Afee");
INSERT INTO Musicians (name) VALUES("Johnny Mc Aleese");
INSERT INTO Musicians (name) VALUES("William Allingham");
INSERT INTO Musicians (name) VALUES("Sean Mc Aloon");
INSERT INTO Musicians (name) VALUES("Altan");
INSERT INTO Musicians (name) VALUES("William");
INSERT INTO Musicians (name) VALUES("Bradley M. Angus");
INSERT INTO Musicians (name) VALUES("Tomas Mac Aogain");
INSERT INTO Musicians (name) VALUES("Caoimhin Mac Aoidh");
INSERT INTO Musicians (name) VALUES("Gabriel Mc Ardle");
INSERT INTO Musicians (name) VALUES("Tom Armstrong");
INSERT INTO Musicians (name) VALUES("Davey Arthur");
INSERT INTO Musicians (name) VALUES("Oisin Mc Auley");
INSERT INTO Musicians (name) VALUES("Joe Bane");
INSERT INTO Musicians (name) VALUES("Troy Bannon");
INSERT INTO Musicians (name) VALUES("Cormac de Barra");
INSERT INTO Musicians (name) VALUES("Domhnall de Barra");
INSERT INTO Musicians (name) VALUES("Paddy Barron");
INSERT INTO Musicians (name) VALUES("Christy Barry");
INSERT INTO Musicians (name) VALUES("Garrett Barry");
INSERT INTO Musicians (name) VALUES("Margaret Barry");
INSERT INTO Musicians (name) VALUES("Majella Bartley");
INSERT INTO Musicians (name) VALUES("Pat Barton");
INSERT INTO Musicians (name) VALUES("Tom Barrett");
INSERT INTO Musicians (name) VALUES("John Bass");
INSERT INTO Musicians (name) VALUES("Noel Battle");
INSERT INTO Musicians (name) VALUES("Mai Baxter");
INSERT INTO Musicians (name) VALUES("Paddy Beades");
INSERT INTO Musicians (name) VALUES("Laura Beagon");
INSERT INTO Musicians (name) VALUES("Brendan Begley");
INSERT INTO Musicians (name) VALUES("Eoin Begley");
INSERT INTO Musicians (name) VALUES("Seamus Begley");
INSERT INTO Musicians (name) VALUES("Martin Beirne");
INSERT INTO Musicians (name) VALUES("Mary (nee Conlon) Beirne");
INSERT INTO Musicians (name) VALUES("Derek Bell");
INSERT INTO Musicians (name) VALUES("Jamie Benson");
INSERT INTO Musicians (name) VALUES("Mel Bernard");
INSERT INTO Musicians (name) VALUES("Mary Bergin");
INSERT INTO Musicians (name) VALUES("Paddy Berry");
INSERT INTO Musicians (name) VALUES("Maire Ni Bhaoil");
INSERT INTO Musicians (name) VALUES("Padai (na Ropai) Bhilli");
INSERT INTO Musicians (name) VALUES("Eimear Ní Bhroin");
INSERT INTO Musicians (name) VALUES("Brian Bigley");
INSERT INTO Musicians (name) VALUES("Ciaran Bingham");
INSERT INTO Musicians (name) VALUES("Leslie Bingham");
INSERT INTO Musicians (name) VALUES("Tara Diamond");
INSERT INTO Musicians (name) VALUES("Terry Bingham");
INSERT INTO Musicians (name) VALUES("John Blessing");
INSERT INTO Musicians (name) VALUES("Dan Blue");
INSERT INTO Musicians (name) VALUES("Bernard Bogue");
INSERT INTO Musicians (name) VALUES("Joe Boland");
INSERT INTO Musicians (name) VALUES("Michael Bolton");
INSERT INTO Musicians (name) VALUES("Hughie Bonar");
INSERT INTO Musicians (name) VALUES("Neily Bonnar");
INSERT INTO Musicians (name) VALUES("Bothy Band");
INSERT INTO Musicians (name) VALUES("Louis Boudreault");
INSERT INTO Musicians (name) VALUES("Ciaran Bourke");
INSERT INTO Musicians (name) VALUES("Malachy Bourke");
INSERT INTO Musicians (name) VALUES("John Bowe");
INSERT INTO Musicians (name) VALUES("Meadhbh Boyd");
INSERT INTO Musicians (name) VALUES("Turlach Boylan");
INSERT INTO Musicians (name) VALUES("Barney Boyle");
INSERT INTO Musicians (name) VALUES("Catherine Boyle");
INSERT INTO Musicians (name) VALUES("Charlie Boyle");
INSERT INTO Musicians (name) VALUES("Con Boyle");
INSERT INTO Musicians (name) VALUES("Denise Boyle");
INSERT INTO Musicians (name) VALUES("Geraldine Boyle");
INSERT INTO Musicians (name) VALUES("Jim Boyle");
INSERT INTO Musicians (name) VALUES("John Boyle");
INSERT INTO Musicians (name) VALUES("John Patrick Boyle");
INSERT INTO Musicians (name) VALUES("Johnnie (The Sergent) Boyle");
INSERT INTO Musicians (name) VALUES("Nancy Boyle");
INSERT INTO Musicians (name) VALUES("Neillidh Boyle");
INSERT INTO Musicians (name) VALUES("Paddy Boyle");
INSERT INTO Musicians (name) VALUES("Vincent “Vincie” Boyle");
INSERT INTO Musicians (name) VALUES("Harry Bradley");
INSERT INTO Musicians (name) VALUES("Maurice Bradley");
INSERT INTO Musicians (name) VALUES("Paul Bradley");
INSERT INTO Musicians (name) VALUES("Harry Bradshaw");
INSERT INTO Musicians (name) VALUES("Attracta Brady");
INSERT INTO Musicians (name) VALUES("John Brady");
INSERT INTO Musicians (name) VALUES("Paul Brady");
INSERT INTO Musicians (name) VALUES("Brendan Breathnach");
INSERT INTO Musicians (name) VALUES("Cormac Breatnach");
INSERT INTO Musicians (name) VALUES("Marie Breathnach");
INSERT INTO Musicians (name) VALUES("Paddy Breen");
INSERT INTO Musicians (name) VALUES("Philip Breen");
INSERT INTO Musicians (name) VALUES("Schooner Breen");
INSERT INTO Musicians (name) VALUES("Tara Breen");
INSERT INTO Musicians (name) VALUES("Darren Breslin");
INSERT INTO Musicians (name) VALUES("Gerry Breslin");
INSERT INTO Musicians (name) VALUES("John Breslin");
INSERT INTO Musicians (name) VALUES("Paul Brock");
INSERT INTO Musicians (name) VALUES("Ethna Broderick");
INSERT INTO Musicians (name) VALUES("Pat Broderick");
INSERT INTO Musicians (name) VALUES("Peter Broderick");
INSERT INTO Musicians (name) VALUES("Vincent Broderick");
INSERT INTO Musicians (name) VALUES("Peader Broe");
INSERT INTO Musicians (name) VALUES("Arty Brogan");
INSERT INTO Musicians (name) VALUES("John Brogan");
INSERT INTO Musicians (name) VALUES("Mary Brogan");
INSERT INTO Musicians (name) VALUES("Sonny Brogan");
INSERT INTO Musicians (name) VALUES("Jim Brophy");
INSERT INTO Musicians (name) VALUES("Pat Brophy");
INSERT INTO Musicians (name) VALUES("Mick Brown");
INSERT INTO Musicians (name) VALUES("Peter Browne");
INSERT INTO Musicians (name) VALUES("Ronan Browne");
INSERT INTO Musicians (name) VALUES("Edward Bunting");
INSERT INTO Musicians (name) VALUES("Claire Burke");
INSERT INTO Musicians (name) VALUES("Dermot Burke");
INSERT INTO Musicians (name) VALUES("Joe (Banjo) Burke");
INSERT INTO Musicians (name) VALUES("Joe Burke");
INSERT INTO Musicians (name) VALUES("Kevin Burke");
INSERT INTO Musicians (name) VALUES("Ciaran Burns");
INSERT INTO Musicians (name) VALUES("Tom Busby");
INSERT INTO Musicians (name) VALUES("Fiona Butler");
INSERT INTO Musicians (name) VALUES("Gerard Butler");
INSERT INTO Musicians (name) VALUES("Pa Butler");
INSERT INTO Musicians (name) VALUES("Alan Byrne");
INSERT INTO Musicians (name) VALUES("Clare Byrne");
INSERT INTO Musicians (name) VALUES("Connie (Drost) Byrne");
INSERT INTO Musicians (name) VALUES("Conor Byrne");
INSERT INTO Musicians (name) VALUES("Danny Byrne");
INSERT INTO Musicians (name) VALUES("Frank Byrne");
INSERT INTO Musicians (name) VALUES("James Byrne");
INSERT INTO Musicians (name) VALUES("Jemmy Byrne");
INSERT INTO Musicians (name) VALUES("John Byrne");
INSERT INTO Musicians (name) VALUES("John Byrne");
INSERT INTO Musicians (name) VALUES("Johnnie Byrne");
INSERT INTO Musicians (name) VALUES("Nora Byrne");
INSERT INTO Musicians (name) VALUES("Packie Manus Byrne");
INSERT INTO Musicians (name) VALUES("Paddy Byrne");
INSERT INTO Musicians (name) VALUES("Peadar hIghne Byrne");
INSERT INTO Musicians (name) VALUES("Tony Byrne");
INSERT INTO Musicians (name) VALUES("Ursula Byrne");
INSERT INTO Musicians (name) VALUES("Dermot Byrnes");
INSERT INTO Musicians (name) VALUES("Martin Byrnes");
INSERT INTO Musicians (name) VALUES("George Byrt");
INSERT INTO Musicians (name) VALUES("Bridget Caden");
INSERT INTO Musicians (name) VALUES("Padraigin Caesar");
INSERT INTO Musicians (name) VALUES("Eddie Cahill");
INSERT INTO Musicians (name) VALUES("Maude Caitlin");
INSERT INTO Musicians (name) VALUES("John Callaghan");
INSERT INTO Musicians (name) VALUES("Mick Callaghan");
INSERT INTO Musicians (name) VALUES("Columba Campbell");
INSERT INTO Musicians (name) VALUES("James Campbell");
INSERT INTO Musicians (name) VALUES("Jimmy Campbell");
INSERT INTO Musicians (name) VALUES("Josie Campbell");
INSERT INTO Musicians (name) VALUES("Peter Campbell");
INSERT INTO Musicians (name) VALUES("Peter Campbell");
INSERT INTO Musicians (name) VALUES("Vincent Campbell");
INSERT INTO Musicians (name) VALUES("Catriona Cannon");
INSERT INTO Musicians (name) VALUES("Cormack Cannon");
INSERT INTO Musicians (name) VALUES("Paddy Canny");
INSERT INTO Musicians (name) VALUES("Peter Carberry");
INSERT INTO Musicians (name) VALUES("Harry Carey");
INSERT INTO Musicians (name) VALUES("Tom Carey");
INSERT INTO Musicians (name) VALUES("Jean Carignan");
INSERT INTO Musicians (name) VALUES("John Carlos");
INSERT INTO Musicians (name) VALUES("Shane Carlos");
INSERT INTO Musicians (name) VALUES("Michael Carney");
INSERT INTO Musicians (name) VALUES("Mary Anne Carolan");
INSERT INTO Musicians (name) VALUES("Nicholas Carolan");
INSERT INTO Musicians (name) VALUES("William Carolan");
INSERT INTO Musicians (name) VALUES("Charlie Carr");
INSERT INTO Musicians (name) VALUES("Michael");
INSERT INTO Musicians (name) VALUES("Dr. Peter Carr");
INSERT INTO Musicians (name) VALUES("Proinsias Carr");
INSERT INTO Musicians (name) VALUES("John Carrol");
INSERT INTO Musicians (name) VALUES("John Carroll");
INSERT INTO Musicians (name) VALUES("Liz Carroll");
INSERT INTO Musicians (name) VALUES("Michael Carroll");
INSERT INTO Musicians (name) VALUES("Ciaran Carson");
INSERT INTO Musicians (name) VALUES("Angela Carty");
INSERT INTO Musicians (name) VALUES("Batty Carty");
INSERT INTO Musicians (name) VALUES("James Carty");
INSERT INTO Musicians (name) VALUES("John Carty");
INSERT INTO Musicians (name) VALUES("John Snr. P Carty");
INSERT INTO Musicians (name) VALUES("Paddy Carty");
INSERT INTO Musicians (name) VALUES("Bobby Casey");
INSERT INTO Musicians (name) VALUES("John Scully Casey");
INSERT INTO Musicians (name) VALUES("Seamus Casey");
INSERT INTO Musicians (name) VALUES("Thady Casey");
INSERT INTO Musicians (name) VALUES("James Cash");
INSERT INTO Musicians (name) VALUES("John Cash");
INSERT INTO Musicians (name) VALUES("Francis Cashin");
INSERT INTO Musicians (name) VALUES("Michael J. Cashin");
INSERT INTO Musicians (name) VALUES("Jimmy Casserly");
INSERT INTO Musicians (name) VALUES("Mick Casserly");
INSERT INTO Musicians (name) VALUES("Con Cassidy");
INSERT INTO Musicians (name) VALUES("Frank Cassidy");
INSERT INTO Musicians (name) VALUES("Jimmy Cassidy");
INSERT INTO Musicians (name) VALUES("Joe Cassidy");
INSERT INTO Musicians (name) VALUES("Johnnie Cassidy");
INSERT INTO Musicians (name) VALUES("Paddy Cassidy");
INSERT INTO Musicians (name) VALUES("Tom Cawley");
INSERT INTO Musicians (name) VALUES("John (Jakes) Cawley");
INSERT INTO Musicians (name) VALUES("Maggie Murphy (Chambers)");
INSERT INTO Musicians (name) VALUES("Nicola Ni Chathail");
INSERT INTO Musicians (name) VALUES("Niamh Ni Charra");
INSERT INTO Musicians (name) VALUES("Freda Nic Ghiolla Chathain");
INSERT INTO Musicians (name) VALUES("Maire Ni Chathasaigh");
INSERT INTO Musicians (name) VALUES("Nollaig Ni Chathasaigh");
INSERT INTO Musicians (name) VALUES("Treasa Ni Cheannabhain");
INSERT INTO Musicians (name) VALUES("Sharon Ní Chearbhall");
INSERT INTO Musicians (name) VALUES("Maire Ni Cheochain");
INSERT INTO Musicians (name) VALUES("Rab Cherry");
INSERT INTO Musicians (name) VALUES("Chieftans");
INSERT INTO Musicians (name) VALUES("Sean John Chit");
INSERT INTO Musicians (name) VALUES("Catriona Ni Chlochasaigh");
INSERT INTO Musicians (name) VALUES("Neansai Ni Choisdealbha");
INSERT INTO Musicians (name) VALUES("Nell Ni Chroinin");
INSERT INTO Musicians (name) VALUES("Eilis ni Chonghaile");
INSERT INTO Musicians (name) VALUES("Cait Ní Chuis");
INSERT INTO Musicians (name) VALUES("Robert Cinnamond");
INSERT INTO Musicians (name) VALUES("Brendan Clancy");
INSERT INTO Musicians (name) VALUES("Geraldine Clancy");
INSERT INTO Musicians (name) VALUES("Gilbert");
INSERT INTO Musicians (name) VALUES("Liam Clancy");
INSERT INTO Musicians (name) VALUES("Martha Clancy");
INSERT INTO Musicians (name) VALUES("Mary");
INSERT INTO Musicians (name) VALUES("Noel Clancy");
INSERT INTO Musicians (name) VALUES("Paddy Clancy");
INSERT INTO Musicians (name) VALUES("Tomas Clancy");
INSERT INTO Musicians (name) VALUES("Willie Clancy");
INSERT INTO Musicians (name) VALUES("Eddie Clarke");
INSERT INTO Musicians (name) VALUES("Robert William Clarke");
INSERT INTO Musicians (name) VALUES("Tom Clarke");
INSERT INTO Musicians (name) VALUES("Michael Clarkson");
INSERT INTO Musicians (name) VALUES("Bill Cleary");
INSERT INTO Musicians (name) VALUES("Dan Cleary");
INSERT INTO Musicians (name) VALUES("George Cleary");
INSERT INTO Musicians (name) VALUES("Nora Cleary");
INSERT INTO Musicians (name) VALUES("Billy Clifford");
INSERT INTO Musicians (name) VALUES("John Clifford");
INSERT INTO Musicians (name) VALUES("Julia Clifford");
INSERT INTO Musicians (name) VALUES("Fr. Charles Coen");
INSERT INTO Musicians (name) VALUES("Jack Coen");
INSERT INTO Musicians (name) VALUES("Aidan Coffey");
INSERT INTO Musicians (name) VALUES("Maire de Cogain");
INSERT INTO Musicians (name) VALUES("Bernadette Collins");
INSERT INTO Musicians (name) VALUES("Brian Collins");
INSERT INTO Musicians (name) VALUES("Kathleen Collins");
INSERT INTO Musicians (name) VALUES("Marion Collins");
INSERT INTO Musicians (name) VALUES("Michael Collins");
INSERT INTO Musicians (name) VALUES("Siobhan Collins");
INSERT INTO Musicians (name) VALUES("Tim Collins");
INSERT INTO Musicians (name) VALUES("Tim Collins");
INSERT INTO Musicians (name) VALUES("James Coleman");
INSERT INTO Musicians (name) VALUES("Jim Coleman");
INSERT INTO Musicians (name) VALUES("Michael Coleman");
INSERT INTO Musicians (name) VALUES("Willie Coleman");
INSERT INTO Musicians (name) VALUES("Ellen Flanagan Comerford");
INSERT INTO Musicians (name) VALUES("Gerdie Commane");
INSERT INTO Musicians (name) VALUES("Verena Commins");
INSERT INTO Musicians (name) VALUES("Barney (Fireman) Conlon");
INSERT INTO Musicians (name) VALUES("Peter James Conlon");
INSERT INTO Musicians (name) VALUES("Rose Murphy (nee Conlon)");
INSERT INTO Musicians (name) VALUES("Clair Connaghan");
INSERT INTO Musicians (name) VALUES("John James Connaghan");
INSERT INTO Musicians (name) VALUES("Neville Connaghan");
INSERT INTO Musicians (name) VALUES("Patrick Connaghan");
INSERT INTO Musicians (name) VALUES("Tara Connaghan");
INSERT INTO Musicians (name) VALUES("Mick Conneely");
INSERT INTO Musicians (name) VALUES("Kevin Conneff");
INSERT INTO Musicians (name) VALUES("Johnny Connolly");
INSERT INTO Musicians (name) VALUES("Mattie Connolly");
INSERT INTO Musicians (name) VALUES("Maura Connolly");
INSERT INTO Musicians (name) VALUES("Seamus Connolly");
INSERT INTO Musicians (name) VALUES("Eugene Connor");
INSERT INTO Musicians (name) VALUES("Andy Conroy");
INSERT INTO Musicians (name) VALUES("Kieran Convery");
INSERT INTO Musicians (name) VALUES("Jim Conway");
INSERT INTO Musicians (name) VALUES("J.J. Conway");
INSERT INTO Musicians (name) VALUES("Ollie Conway");
INSERT INTO Musicians (name) VALUES("Sean Conway");
INSERT INTO Musicians (name) VALUES("Zoe Conway");
INSERT INTO Musicians (name) VALUES("James Coogan");
INSERT INTO Musicians (name) VALUES("Mary Coogan");
INSERT INTO Musicians (name) VALUES("Joe cooley");
INSERT INTO Musicians (name) VALUES("Seamus Cooley");
INSERT INTO Musicians (name) VALUES("Martin Cooney");
INSERT INTO Musicians (name) VALUES("Michael Cooney");
INSERT INTO Musicians (name) VALUES("Quentin Cooper");
INSERT INTO Musicians (name) VALUES("Mary Corcoran");
INSERT INTO Musicians (name) VALUES("Ciara Ni Coring");
INSERT INTO Musicians (name) VALUES("Jimmy Cormac");
INSERT INTO Musicians (name) VALUES("Rachel Corr");
INSERT INTO Musicians (name) VALUES("Mairead Corridan");
INSERT INTO Musicians (name) VALUES("Willie Corrigan");
INSERT INTO Musicians (name) VALUES("Jim Corry");
INSERT INTO Musicians (name) VALUES("Cecilia Costello");
INSERT INTO Musicians (name) VALUES("Pat Costello");
INSERT INTO Musicians (name) VALUES("Eamon Cotter");
INSERT INTO Musicians (name) VALUES("Geraldine Cotter");
INSERT INTO Musicians (name) VALUES("Danny Coughlan");
INSERT INTO Musicians (name) VALUES("Charlie Cox");
INSERT INTO Musicians (name) VALUES("Eamonn Coyne");
INSERT INTO Musicians (name) VALUES("Eamon Coyne");
INSERT INTO Musicians (name) VALUES("Maurice Coyne");
INSERT INTO Musicians (name) VALUES("Michael Coyne");
INSERT INTO Musicians (name) VALUES("Mick");
INSERT INTO Musicians (name) VALUES("Paul Coyne");
INSERT INTO Musicians (name) VALUES("Terry Coyne");
INSERT INTO Musicians (name) VALUES("Johnnie Crampsie");
INSERT INTO Musicians (name) VALUES("Matt Cranitch");
INSERT INTO Musicians (name) VALUES("John Crawford Snr.");
INSERT INTO Musicians (name) VALUES("Kevin Crawford");
INSERT INTO Musicians (name) VALUES("Seamus Creagh");
INSERT INTO Musicians (name) VALUES("John Creaven");
INSERT INTO Musicians (name) VALUES("Angela Crehan");
INSERT INTO Musicians (name) VALUES("Cissie nee Walsh Crehan");
INSERT INTO Musicians (name) VALUES("Ita Crehan");
INSERT INTO Musicians (name) VALUES("Kieran Crehan");
INSERT INTO Musicians (name) VALUES("Margaret Crehan");
INSERT INTO Musicians (name) VALUES("Martin (Junior) Crehan");
INSERT INTO Musicians (name) VALUES("Tony Crehan");
INSERT INTO Musicians (name) VALUES("Vincent Crehan");
INSERT INTO Musicians (name) VALUES("Richard Creasey");
INSERT INTO Musicians (name) VALUES("Sharon Creasey");
INSERT INTO Musicians (name) VALUES("Dan Cronin");
INSERT INTO Musicians (name) VALUES("Elizabeth (Bess) Cronin");
INSERT INTO Musicians (name) VALUES("Johnny Cronin");
INSERT INTO Musicians (name) VALUES("Paddy Cronin");
INSERT INTO Musicians (name) VALUES("Martin Crossin");
INSERT INTO Musicians (name) VALUES("Angela nee Crehan Crotty");
INSERT INTO Musicians (name) VALUES("Elizabeth (Markham) Crotty");
INSERT INTO Musicians (name) VALUES("P.J. Crotty");
INSERT INTO Musicians (name) VALUES("Jimmy Crowley");
INSERT INTO Musicians (name) VALUES("P. Crowley");
INSERT INTO Musicians (name) VALUES("Vincent Crowley");
INSERT INTO Musicians (name) VALUES("James Cullinane");
INSERT INTO Musicians (name) VALUES("Caitrona Cullivan");
INSERT INTO Musicians (name) VALUES("William Cummins");
INSERT INTO Musicians (name) VALUES("Alphie Cunnea");
INSERT INTO Musicians (name) VALUES("Con Cunnea");
INSERT INTO Musicians (name) VALUES("Davey Cunnea");
INSERT INTO Musicians (name) VALUES("Gerry Cunnea");
INSERT INTO Musicians (name) VALUES("Tommie Cunniffe");
INSERT INTO Musicians (name) VALUES("Audrey Cunningham");
INSERT INTO Musicians (name) VALUES("Ita Cunningham");
INSERT INTO Musicians (name) VALUES("Matt Cunningham");
INSERT INTO Musicians (name) VALUES("Pat Cunningham");
INSERT INTO Musicians (name) VALUES("Pat Cunningham");
INSERT INTO Musicians (name) VALUES("Peter Cunningham");
INSERT INTO Musicians (name) VALUES("Thomas Cunningham");
INSERT INTO Musicians (name) VALUES("Ciaran Curren");
INSERT INTO Musicians (name) VALUES("Cyril Curran");
INSERT INTO Musicians (name) VALUES("Murt Curren");
INSERT INTO Musicians (name) VALUES("Ned Curren");
INSERT INTO Musicians (name) VALUES("Tom Cussen");
INSERT INTO Musicians (name) VALUES("Catherine Custy");
INSERT INTO Musicians (name) VALUES("Ellen Custy");
INSERT INTO Musicians (name) VALUES("Frances Custy");
INSERT INTO Musicians (name) VALUES("Frank Custy");
INSERT INTO Musicians (name) VALUES("Mary Custy");
INSERT INTO Musicians (name) VALUES("Tola Custy");
INSERT INTO Musicians (name) VALUES("Gregory Daly");
INSERT INTO Musicians (name) VALUES("Jackie Daly");
INSERT INTO Musicians (name) VALUES("John Daly");
INSERT INTO Musicians (name) VALUES("Patricia Daly");
INSERT INTO Musicians (name) VALUES("Stephen Daly");
INSERT INTO Musicians (name) VALUES("Patrick D’Arcy");
INSERT INTO Musicians (name) VALUES("Arthur Warren Darley");
INSERT INTO Musicians (name) VALUES("Andrew Davey");
INSERT INTO Musicians (name) VALUES("Andrew Junior Davey");
INSERT INTO Musicians (name) VALUES("Dominic Davey");
INSERT INTO Musicians (name) VALUES("James (Sonny) Davey");
INSERT INTO Musicians (name) VALUES("Margaret Davey");
INSERT INTO Musicians (name) VALUES("Seana Ní Dhaithí");
INSERT INTO Musicians (name) VALUES("David");
INSERT INTO Musicians (name) VALUES("Conor Day");
INSERT INTO Musicians (name) VALUES("De Dannan");
INSERT INTO Musicians (name) VALUES("Sandra Deegan");
INSERT INTO Musicians (name) VALUES("Bernard Delaney");
INSERT INTO Musicians (name) VALUES("Dinny Delaney");
INSERT INTO Musicians (name) VALUES("Sean Dempsey");
INSERT INTO Musicians (name) VALUES("Tim Dennehy");
INSERT INTO Musicians (name) VALUES("Joe Derrane");
INSERT INTO Musicians (name) VALUES("Dervish");
INSERT INTO Musicians (name) VALUES("Hughie Devanney");
INSERT INTO Musicians (name) VALUES("Seana Ní Dhaithí");
INSERT INTO Musicians (name) VALUES("Maighread Ni Dhomhnaill");
INSERT INTO Musicians (name) VALUES("Neill Ni Dhomhnaill");
INSERT INTO Musicians (name) VALUES("Triona Ni Dhomhnaill");
INSERT INTO Musicians (name) VALUES("Eithne Ni Dhonaile");
INSERT INTO Musicians (name) VALUES("Maire Aine Ni Dhonnchadha");
INSERT INTO Musicians (name) VALUES("Marie Nic Dhonnchadha");
INSERT INTO Musicians (name) VALUES("Roisin Nic Dhonnacha");
INSERT INTO Musicians (name) VALUES("Dermie Diamond");
INSERT INTO Musicians (name) VALUES("Tara (Bingham) Diamond");
INSERT INTO Musicians (name) VALUES("Mary Dillon");
INSERT INTO Musicians (name) VALUES("Oliver Diviney");
INSERT INTO Musicians (name) VALUES("Charlie Doherty");
INSERT INTO Musicians (name) VALUES("Christie Doherty");
INSERT INTO Musicians (name) VALUES("Fanny Doherty");
INSERT INTO Musicians (name) VALUES("Hugh Doherty");
INSERT INTO Musicians (name) VALUES("Hugh Doherty");
INSERT INTO Musicians (name) VALUES("John Doherty");
INSERT INTO Musicians (name) VALUES("Jeannie (Mc Glynn) Doherty");
INSERT INTO Musicians (name) VALUES("Liz Doherty");
INSERT INTO Musicians (name) VALUES("Michael Doherty");
INSERT INTO Musicians (name) VALUES("Michael Doherty");
INSERT INTO Musicians (name) VALUES("Mickey Doherty");
INSERT INTO Musicians (name) VALUES("Neil Doherty");
INSERT INTO Musicians (name) VALUES("Patrick Doherty");
INSERT INTO Musicians (name) VALUES("Simon Doherty");
INSERT INTO Musicians (name) VALUES("Simon Doherty");
INSERT INTO Musicians (name) VALUES("Simon Doherty");
INSERT INTO Musicians (name) VALUES("Stephen Doherty");
INSERT INTO Musicians (name) VALUES("Tom Doherty");
INSERT INTO Musicians (name) VALUES("Charlie Dolan");
INSERT INTO Musicians (name) VALUES("Charlie Snr. Dolan");
INSERT INTO Musicians (name) VALUES("Charlie jnr. Dolan");
INSERT INTO Musicians (name) VALUES("Jack Dolan");
INSERT INTO Musicians (name) VALUES("James Dolan");
INSERT INTO Musicians (name) VALUES("John Dolan");
INSERT INTO Musicians (name) VALUES("Packie Dolan");
INSERT INTO Musicians (name) VALUES("Christina Dolphin");
INSERT INTO Musicians (name) VALUES("Frances Donahue");
INSERT INTO Musicians (name) VALUES("Frances Donahue");
INSERT INTO Musicians (name) VALUES("Padraig Donlon");
INSERT INTO Musicians (name) VALUES("Jim Donoghue");
INSERT INTO Musicians (name) VALUES("Joe Donoghue");
INSERT INTO Musicians (name) VALUES("Jackie Donnan");
INSERT INTO Musicians (name) VALUES("Francie Donnellan");
INSERT INTO Musicians (name) VALUES("Johnny Donnellan");
INSERT INTO Musicians (name) VALUES("Mark Donnellan");
INSERT INTO Musicians (name) VALUES("Des Donnelly");
INSERT INTO Musicians (name) VALUES("Dezi Donnelly");
INSERT INTO Musicians (name) VALUES("Liam Donnelly");
INSERT INTO Musicians (name) VALUES("Maeve Donnelly");
INSERT INTO Musicians (name) VALUES("Mark Donnelly");
INSERT INTO Musicians (name) VALUES("Sean Donnelly");
INSERT INTO Musicians (name) VALUES("Denis Doody");
INSERT INTO Musicians (name) VALUES("Barney Doogan");
INSERT INTO Musicians (name) VALUES("Bob Doogan");
INSERT INTO Musicians (name) VALUES("John Doogan");
INSERT INTO Musicians (name) VALUES("Tom Doorley");
INSERT INTO Musicians (name) VALUES("Felix Doran");
INSERT INTO Musicians (name) VALUES("Johnny Doran");
INSERT INTO Musicians (name) VALUES("Mikey Doran");
INSERT INTO Musicians (name) VALUES("Joey Doyle");
INSERT INTO Musicians (name) VALUES("Martin Doyle");
INSERT INTO Musicians (name) VALUES("Tom Doyle");
INSERT INTO Musicians (name) VALUES("Michael Dow");
INSERT INTO Musicians (name) VALUES("Dan Dowd");
INSERT INTO Musicians (name) VALUES("Martin Dowling");
INSERT INTO Musicians (name) VALUES("Michael Downes");
INSERT INTO Musicians (name) VALUES("Chris Droney");
INSERT INTO Musicians (name) VALUES("Eddie Duffy");
INSERT INTO Musicians (name) VALUES("Eugene Duffy");
INSERT INTO Musicians (name) VALUES("John Duffy");
INSERT INTO Musicians (name) VALUES("Johnny Duffy");
INSERT INTO Musicians (name) VALUES("Philip Duffy");
INSERT INTO Musicians (name) VALUES("Philip Duffy");
INSERT INTO Musicians (name) VALUES("Alf Duggan");
INSERT INTO Musicians (name) VALUES("Packie Duignan");
INSERT INTO Musicians (name) VALUES("Brid Dunne");
INSERT INTO Musicians (name) VALUES("Catherine Dunne");
INSERT INTO Musicians (name) VALUES("Christy");
INSERT INTO Musicians (name) VALUES("Johnjo Dunne");
INSERT INTO Musicians (name) VALUES("Micky Dunne");
INSERT INTO Musicians (name) VALUES("Niamh Dunne");
INSERT INTO Musicians (name) VALUES("Paddy Dunne");
INSERT INTO Musicians (name) VALUES("Paddy (Pecker) Dunne");
INSERT INTO Musicians (name) VALUES("Molly Durkin");
INSERT INTO Musicians (name) VALUES("Billy Dwyer");
INSERT INTO Musicians (name) VALUES("Finbar Dwyer");
INSERT INTO Musicians (name) VALUES("John Dwyer");
INSERT INTO Musicians (name) VALUES("Michael Dwyer");
INSERT INTO Musicians (name) VALUES("Seacailín Ní Ealaithe");
INSERT INTO Musicians (name) VALUES("Ernestine Ni Ealal");
INSERT INTO Musicians (name) VALUES("John Egan");
INSERT INTO Musicians (name) VALUES("Larry Egan");
INSERT INTO Musicians (name) VALUES("Tom Egan");
INSERT INTO Musicians (name) VALUES("Naisrin El Safti");
INSERT INTO Musicians (name) VALUES("James Ennis");
INSERT INTO Musicians (name) VALUES("John Ennis");
INSERT INTO Musicians (name) VALUES("Seamus Ennis");
INSERT INTO Musicians (name) VALUES("Tom Ennis");
INSERT INTO Musicians (name) VALUES("Amanda Nic Eochaidh");
INSERT INTO Musicians (name) VALUES("Bridget (McKeon) Owens");
INSERT INTO Musicians (name) VALUES("Paddy Owens");
INSERT INTO Musicians (name) VALUES("Paddy Fahey");
INSERT INTO Musicians (name) VALUES("John Joe Fahy");
INSERT INTO Musicians (name) VALUES("Sinead Fahy");
INSERT INTO Musicians (name) VALUES("Dave Fallon");
INSERT INTO Musicians (name) VALUES("Frank Fallon");
INSERT INTO Musicians (name) VALUES("Joe Fallon");
INSERT INTO Musicians (name) VALUES("Martin Fallon");
INSERT INTO Musicians (name) VALUES("Frank Fannon");
INSERT INTO Musicians (name) VALUES("Farley \"The Bearded Fiddler\"");
INSERT INTO Musicians (name) VALUES("Lucy Farr");
INSERT INTO Musicians (name) VALUES("Redmond Farragher");
INSERT INTO Musicians (name) VALUES("John Farrell");
INSERT INTO Musicians (name) VALUES("Liam Farrell");
INSERT INTO Musicians (name) VALUES("Patsy Farrell");
INSERT INTO Musicians (name) VALUES("Martin Fay");
INSERT INTO Musicians (name) VALUES("Prof. Aloys Fleischman");
INSERT INTO Musicians (name) VALUES("Tom Ferris");
INSERT INTO Musicians (name) VALUES("Hubert Finan");
INSERT INTO Musicians (name) VALUES("Alec Finn");
INSERT INTO Musicians (name) VALUES("Billy Finn");
INSERT INTO Musicians (name) VALUES("Fred Finn");
INSERT INTO Musicians (name) VALUES("Pat Finn");
INSERT INTO Musicians (name) VALUES("Paul Finn");
INSERT INTO Musicians (name) VALUES("Brian Finnegan");
INSERT INTO Musicians (name) VALUES("Fergus Finnegan");
INSERT INTO Musicians (name) VALUES("Ursula Finnegan");
INSERT INTO Musicians (name) VALUES("Claire Fitzpatrick");
INSERT INTO Musicians (name) VALUES("Pat Fitzpatrick");
INSERT INTO Musicians (name) VALUES("Patrick Fitzpatrick");
INSERT INTO Musicians (name) VALUES("Larry Wall Fitzpatrick");
INSERT INTO Musicians (name) VALUES("Sarah Fitzpatrick");
INSERT INTO Musicians (name) VALUES("Flanagan");
INSERT INTO Musicians (name) VALUES("Austin Flanagan");
INSERT INTO Musicians (name) VALUES("Dominick ‘Sonny’ Flanagan");
INSERT INTO Musicians (name) VALUES("Joe Flanagan");
INSERT INTO Musicians (name) VALUES("Johnny Flanagan");
INSERT INTO Musicians (name) VALUES("Mike Flanagan");
INSERT INTO Musicians (name) VALUES("Michael “Straighty”Flanagan");
INSERT INTO Musicians (name) VALUES("Michael Flanagan");
INSERT INTO Musicians (name) VALUES("Louis Flanagan");
INSERT INTO Musicians (name) VALUES("Peter Flanagan");
INSERT INTO Musicians (name) VALUES("Michael Flanigan");
INSERT INTO Musicians (name) VALUES("Michael Flatley");
INSERT INTO Musicians (name) VALUES("Tracey Fleming");
INSERT INTO Musicians (name) VALUES("Kieran Fletcher");
INSERT INTO Musicians (name) VALUES("William H Grattan Flood");
INSERT INTO Musicians (name) VALUES("Aidan Flynn");
INSERT INTO Musicians (name) VALUES("Johnnie Flynn");
INSERT INTO Musicians (name) VALUES("Mike Flynn");
INSERT INTO Musicians (name) VALUES("Peter Flynn");
INSERT INTO Musicians (name) VALUES("Tommy Flynn");
INSERT INTO Musicians (name) VALUES("Willie Fogarty");
INSERT INTO Musicians (name) VALUES("Declan Folan");
INSERT INTO Musicians (name) VALUES("Kathleen Ford");
INSERT INTO Musicians (name) VALUES("Gerry Forde");
INSERT INTO Musicians (name) VALUES("William Forde");
INSERT INTO Musicians (name) VALUES("Edel Fox");
INSERT INTO Musicians (name) VALUES("Martin Frain");
INSERT INTO Musicians (name) VALUES("Dan Furey");
INSERT INTO Musicians (name) VALUES("Eddie Furey");
INSERT INTO Musicians (name) VALUES("Finbar Furey");
INSERT INTO Musicians (name) VALUES("George Furey");
INSERT INTO Musicians (name) VALUES("Nora (Connolly) Furey");
INSERT INTO Musicians (name) VALUES("Paul Furey");
INSERT INTO Musicians (name) VALUES("Ted Furey");
INSERT INTO Musicians (name) VALUES("Mick Furlong");
INSERT INTO Musicians (name) VALUES("Caitlin Nic Gabhann");
INSERT INTO Musicians (name) VALUES("Martin Gaffney");
INSERT INTO Musicians (name) VALUES("Michael Gaffney");
INSERT INTO Musicians (name) VALUES("Aoife Gallagher");
INSERT INTO Musicians (name) VALUES("Connie Gallagher");
INSERT INTO Musicians (name) VALUES("Croidhe Gallagher");
INSERT INTO Musicians (name) VALUES("Eithne Gallagher");
INSERT INTO Musicians (name) VALUES("Hughie Gallagher");
INSERT INTO Musicians (name) VALUES("Joe Gallagher");
INSERT INTO Musicians (name) VALUES("John (the Tae) Gallagher");
INSERT INTO Musicians (name) VALUES("Michael Gallagher");
INSERT INTO Musicians (name) VALUES("Michael Gallagher");
INSERT INTO Musicians (name) VALUES("Niamh Gallagher");
INSERT INTO Musicians (name) VALUES("Paddy (the Tae) Gallagher");
INSERT INTO Musicians (name) VALUES("Tommy Gallagher");
INSERT INTO Musicians (name) VALUES("Joe Lackey Gallagher");
INSERT INTO Musicians (name) VALUES("Johnnie Gallagher");
INSERT INTO Musicians (name) VALUES("John Gallagher");
INSERT INTO Musicians (name) VALUES("Mickey Gallagher");
INSERT INTO Musicians (name) VALUES("Bernard Galligan");
INSERT INTO Musicians (name) VALUES("Ellen Nell (nee McCarthy) Galvan");
INSERT INTO Musicians (name) VALUES("Patrick Galvin");
INSERT INTO Musicians (name) VALUES("Ronan Galvin");
INSERT INTO Musicians (name) VALUES("Roy Galvin");
INSERT INTO Musicians (name) VALUES("Stephen Galvin");
INSERT INTO Musicians (name) VALUES("James Gandsey");
INSERT INTO Musicians (name) VALUES("Tom Ganley");
INSERT INTO Musicians (name) VALUES("James Gannon");
INSERT INTO Musicians (name) VALUES("Jamesy Gannon");
INSERT INTO Musicians (name) VALUES("John Joe Gannon");
INSERT INTO Musicians (name) VALUES("Tom Gannon");
INSERT INTO Musicians (name) VALUES("Michael Gara");
INSERT INTO Musicians (name) VALUES("Bobby Gardiner");
INSERT INTO Musicians (name) VALUES("John Joe Gardiner");
INSERT INTO Musicians (name) VALUES("Thomas Garoghan");
INSERT INTO Musicians (name) VALUES("Liam Gaul");
INSERT INTO Musicians (name) VALUES("Frank Gavigan");
INSERT INTO Musicians (name) VALUES("James Gavigan");
INSERT INTO Musicians (name) VALUES("Joe Gavigan");
INSERT INTO Musicians (name) VALUES("Frankie Gavin");
INSERT INTO Musicians (name) VALUES("Larry Gavin");
INSERT INTO Musicians (name) VALUES("Paddy Gavin");
INSERT INTO Musicians (name) VALUES("Maire Ni Ghrada");
INSERT INTO Musicians (name) VALUES("Seamus Gibson");
INSERT INTO Musicians (name) VALUES("Con Gildea");
INSERT INTO Musicians (name) VALUES("John Gildea");
INSERT INTO Musicians (name) VALUES("Pat Gillan");
INSERT INTO Musicians (name) VALUES("Hugh Gillespie");
INSERT INTO Musicians (name) VALUES("Jim Gillespie");
INSERT INTO Musicians (name) VALUES("Johnnie Gillespie");
INSERT INTO Musicians (name) VALUES("Mickey Gillespie");
INSERT INTO Musicians (name) VALUES("Francie Ambrose Given");
INSERT INTO Musicians (name) VALUES("Catherine (O\'Reilly) Glackin");
INSERT INTO Musicians (name) VALUES("Paddy Glackin");
INSERT INTO Musicians (name) VALUES("Tom Glackin");
INSERT INTO Musicians (name) VALUES("Darina Gleeson");
INSERT INTO Musicians (name) VALUES("Michael Anthony Glynn");
INSERT INTO Musicians (name) VALUES("James Goodman");
INSERT INTO Musicians (name) VALUES("Charlie Joe Gordon");
INSERT INTO Musicians (name) VALUES("Francie Gordon");
INSERT INTO Musicians (name) VALUES("John James Gordon");
INSERT INTO Musicians (name) VALUES("John Joe Gordon");
INSERT INTO Musicians (name) VALUES("Johnny (Jack the Piper) Gorman");
INSERT INTO Musicians (name) VALUES("Michael Gorman");
INSERT INTO Musicians (name) VALUES("Ned Gorman");
INSERT INTO Musicians (name) VALUES("Marie (nee Nugent)");
INSERT INTO Musicians (name) VALUES("Brona Graham");
INSERT INTO Musicians (name) VALUES("Len Graham");
INSERT INTO Musicians (name) VALUES("Aoife Granville");
INSERT INTO Musicians (name) VALUES("John Grey");
INSERT INTO Musicians (name) VALUES("Stephen Grier");
INSERT INTO Musicians (name) VALUES("Claire Griffin");
INSERT INTO Musicians (name) VALUES("John Griffin");
INSERT INTO Musicians (name) VALUES("Sean Griffin");
INSERT INTO Musicians (name) VALUES("Vincent Griffin");
INSERT INTO Musicians (name) VALUES("Helena Rowsome");
INSERT INTO Musicians (name) VALUES("Dermot Grogan");
INSERT INTO Musicians (name) VALUES("Michael Grogan");
INSERT INTO Musicians (name) VALUES("Peter Guinan");
INSERT INTO Musicians (name) VALUES("Hugh Gunn");
INSERT INTO Musicians (name) VALUES("John Gunn");
INSERT INTO Musicians (name) VALUES("Katie Gunn");
INSERT INTO Musicians (name) VALUES("Tommy (Jason) Gunn");
INSERT INTO Musicians (name) VALUES("Reg Hall");
INSERT INTO Musicians (name) VALUES("George Halpin");
INSERT INTO Musicians (name) VALUES("Patrick ‘Paddy’ Haly");
INSERT INTO Musicians (name) VALUES("Gráinne Hambly");
INSERT INTO Musicians (name) VALUES("Colin (Hammy) Hamilton");
INSERT INTO Musicians (name) VALUES("Connie Hanafin");
INSERT INTO Musicians (name) VALUES("Micheal Hanafin");
INSERT INTO Musicians (name) VALUES("William (Billy) Hanafin");
INSERT INTO Musicians (name) VALUES("Bill Haneman");
INSERT INTO Musicians (name) VALUES("Gerry Hanley");
INSERT INTO Musicians (name) VALUES("Patsy Hanley");
INSERT INTO Musicians (name) VALUES("Robbie Hannan");
INSERT INTO Musicians (name) VALUES("Joan Hanrahan");
INSERT INTO Musicians (name) VALUES("Kieran Hanrahan");
INSERT INTO Musicians (name) VALUES("Janet Harbison");
INSERT INTO Musicians (name) VALUES("Lesl Harker");
INSERT INTO Musicians (name) VALUES("Frank Harkin");
INSERT INTO Musicians (name) VALUES("Hugh James Harkin");
INSERT INTO Musicians (name) VALUES("Joe Harkin");
INSERT INTO Musicians (name) VALUES("Johnnie Harkin");
INSERT INTO Musicians (name) VALUES("Damien Harrigan");
INSERT INTO Musicians (name) VALUES("Paul Harrigan");
INSERT INTO Musicians (name) VALUES("Roisin Harrigan");
INSERT INTO Musicians (name) VALUES("Gerry Harrington");
INSERT INTO Musicians (name) VALUES("Kathleen Harrington");
INSERT INTO Musicians (name) VALUES("Francis Harrison");
INSERT INTO Musicians (name) VALUES("John Vincent Harrison");
INSERT INTO Musicians (name) VALUES("Mary “Travers” Harrison");
INSERT INTO Musicians (name) VALUES("Michael Harrison");
INSERT INTO Musicians (name) VALUES("Barney Harper");
INSERT INTO Musicians (name) VALUES("Brid Harper");
INSERT INTO Musicians (name) VALUES("Pat Harper");
INSERT INTO Musicians (name) VALUES("Siobhan Harper");
INSERT INTO Musicians (name) VALUES("Stephen Harper");
INSERT INTO Musicians (name) VALUES("Bill Harte");
INSERT INTO Musicians (name) VALUES("Frank Harte");
INSERT INTO Musicians (name) VALUES("Mickey Harvey");
INSERT INTO Musicians (name) VALUES("Pat Harvey");
INSERT INTO Musicians (name) VALUES("Tom Harvey");
INSERT INTO Musicians (name) VALUES("Gerald Haugh");
INSERT INTO Musicians (name) VALUES("Bernard Haughey");
INSERT INTO Musicians (name) VALUES("Connie Haughey");
INSERT INTO Musicians (name) VALUES("Deirdre Havlin");
INSERT INTO Musicians (name) VALUES("Cathal Hayden");
INSERT INTO Musicians (name) VALUES("Joe Hayes");
INSERT INTO Musicians (name) VALUES("Josie Hayes");
INSERT INTO Musicians (name) VALUES("Kitty nee Smith Hayes");
INSERT INTO Musicians (name) VALUES("Martin Hayes");
INSERT INTO Musicians (name) VALUES("P .Joe. Hayes");
INSERT INTO Musicians (name) VALUES("Paddy Hayes");
INSERT INTO Musicians (name) VALUES("Hugh Healy");
INSERT INTO Musicians (name) VALUES("Colm Healy");
INSERT INTO Musicians (name) VALUES("Sinéad Healy");
INSERT INTO Musicians (name) VALUES("Tommy Healy");
INSERT INTO Musicians (name) VALUES("Francie Hegarty");
INSERT INTO Musicians (name) VALUES("Paddy Hegarty");
INSERT INTO Musicians (name) VALUES("Nuala Hehir");
INSERT INTO Musicians (name) VALUES("Anthony Helferty");
INSERT INTO Musicians (name) VALUES("Áine Heneghan");
INSERT INTO Musicians (name) VALUES("Patrick Hennelly");
INSERT INTO Musicians (name) VALUES("Dave Hennessey");
INSERT INTO Musicians (name) VALUES("Batt Henry");
INSERT INTO Musicians (name) VALUES("Carmel (nee Henry) Mc Hale");
INSERT INTO Musicians (name) VALUES("John Henry");
INSERT INTO Musicians (name) VALUES("Kevin Henry");
INSERT INTO Musicians (name) VALUES("Maggie Henry");
INSERT INTO Musicians (name) VALUES("Martin Henry");
INSERT INTO Musicians (name) VALUES("Mary Henry");
INSERT INTO Musicians (name) VALUES("Thomas Henry");
INSERT INTO Musicians (name) VALUES("Johnny Henry");
INSERT INTO Musicians (name) VALUES("Verona Henry");
INSERT INTO Musicians (name) VALUES("Veronica Henry");
INSERT INTO Musicians (name) VALUES("Aine Hensey");
INSERT INTO Musicians (name) VALUES("Dan Herlihy");
INSERT INTO Musicians (name) VALUES("Marcus Hernon");
INSERT INTO Musicians (name) VALUES("Mick Hernon");
INSERT INTO Musicians (name) VALUES("P. J. Hernon");
INSERT INTO Musicians (name) VALUES("Tommy Hester");
INSERT INTO Musicians (name) VALUES("Lorraine Hickey");
INSERT INTO Musicians (name) VALUES("Martin Hickey");
INSERT INTO Musicians (name) VALUES("Charlie Higgins");
INSERT INTO Musicians (name) VALUES("Jim Higgins");
INSERT INTO Musicians (name) VALUES("Noel Hill");
INSERT INTO Musicians (name) VALUES("John Hoban");
INSERT INTO Musicians (name) VALUES("John Hogan");
INSERT INTO Musicians (name) VALUES("Joe Holmes");
INSERT INTO Musicians (name) VALUES("Paddy Homan");
INSERT INTO Musicians (name) VALUES("Peter Horan");
INSERT INTO Musicians (name) VALUES("Seamus Horan");
INSERT INTO Musicians (name) VALUES("Ferard Horgan");
INSERT INTO Musicians (name) VALUES("John Howard");
INSERT INTO Musicians (name) VALUES("Martin Howley");
INSERT INTO Musicians (name) VALUES("Tony Howley");
INSERT INTO Musicians (name) VALUES("Mick Hoy");
INSERT INTO Musicians (name) VALUES("Michael Hubbert");
INSERT INTO Musicians (name) VALUES("Jimmy Hueston");
INSERT INTO Musicians (name) VALUES("Owen Hughes");
INSERT INTO Musicians (name) VALUES("Henry Hudson");
INSERT INTO Musicians (name) VALUES("Mairead Hurley");
INSERT INTO Musicians (name) VALUES("Michael Hunt");
INSERT INTO Musicians (name) VALUES("Tommy Hunt");
INSERT INTO Musicians (name) VALUES("Andy Irvine");
INSERT INTO Musicians (name) VALUES("Eileen Ivers");
INSERT INTO Musicians (name) VALUES("Thomas Jacob");
INSERT INTO Musicians (name) VALUES("Adrian Jefferies");
INSERT INTO Musicians (name) VALUES("Thomas Johnson");
INSERT INTO Musicians (name) VALUES("Tom Johnston");
INSERT INTO Musicians (name) VALUES("Paddy Jones");
INSERT INTO Musicians (name) VALUES("Frank Jordan");
INSERT INTO Musicians (name) VALUES("Mary Ellen (Ford)");
INSERT INTO Musicians (name) VALUES("Pat Jordan");
INSERT INTO Musicians (name) VALUES("Thomas Jordan");
INSERT INTO Musicians (name) VALUES("Tom Jordan");
INSERT INTO Musicians (name) VALUES("Patrick Weston Joyce");
INSERT INTO Musicians (name) VALUES("Eleanor (nee Kane) Neary");
INSERT INTO Musicians (name) VALUES("Liz Kane");
INSERT INTO Musicians (name) VALUES("Yvonne Kane");
INSERT INTO Musicians (name) VALUES("Theresa Kavanagh");
INSERT INTO Musicians (name) VALUES("Conor Keane");
INSERT INTO Musicians (name) VALUES("Dolores Keane");
INSERT INTO Musicians (name) VALUES("Jack Keane");
INSERT INTO Musicians (name) VALUES("James Keane");
INSERT INTO Musicians (name) VALUES("Rita Keane");
INSERT INTO Musicians (name) VALUES("Tommy Keane");
INSERT INTO Musicians (name) VALUES("Sean Keane");
INSERT INTO Musicians (name) VALUES("Felix Kearney");
INSERT INTO Musicians (name) VALUES("Patrick (Packeen) Kearney");
INSERT INTO Musicians (name) VALUES("Tommy Kearney");
INSERT INTO Musicians (name) VALUES("Maeve Kearse");
INSERT INTO Musicians (name) VALUES("Josephine Keegan");
INSERT INTO Musicians (name) VALUES("Niall Keegan");
INSERT INTO Musicians (name) VALUES("Paddy Keenan");
INSERT INTO Musicians (name) VALUES("Tommy Keenan");
INSERT INTO Musicians (name) VALUES("Tommy Keenan");
INSERT INTO Musicians (name) VALUES("Charlie Keeney");
INSERT INTO Musicians (name) VALUES("Eddie Keeney");
INSERT INTO Musicians (name) VALUES("John Parnell Keeney");
INSERT INTO Musicians (name) VALUES("Sonny Keeney");
INSERT INTO Musicians (name) VALUES("Michael Kelleher");
INSERT INTO Musicians (name) VALUES("Mikey Kellehar");
INSERT INTO Musicians (name) VALUES("Alan Kelly");
INSERT INTO Musicians (name) VALUES("Eddie Kelly");
INSERT INTO Musicians (name) VALUES("Francie Kelly");
INSERT INTO Musicians (name) VALUES("Frank Kelly");
INSERT INTO Musicians (name) VALUES("James Kelly");
INSERT INTO Musicians (name) VALUES("Jimmy Kelly");
INSERT INTO Musicians (name) VALUES("John Kelly");
INSERT INTO Musicians (name) VALUES("John Kelly");
INSERT INTO Musicians (name) VALUES("John Jnr Kelly");
INSERT INTO Musicians (name) VALUES("Kieran Kelly");
INSERT INTO Musicians (name) VALUES("Laoise Kelly");
INSERT INTO Musicians (name) VALUES("Liam Kelly");
INSERT INTO Musicians (name) VALUES("Mick Kelly");
INSERT INTO Musicians (name) VALUES("Pat Kelly");
INSERT INTO Musicians (name) VALUES("Pat Kelly");
INSERT INTO Musicians (name) VALUES("Patrick Kelly");
INSERT INTO Musicians (name) VALUES("Fr. Patrick J. Kelly");
INSERT INTO Musicians (name) VALUES("Thomas Kenna");
INSERT INTO Musicians (name) VALUES("Timothy Kenna");
INSERT INTO Musicians (name) VALUES("Frankie Kennedy");
INSERT INTO Musicians (name) VALUES("John Kennedy");
INSERT INTO Musicians (name) VALUES("William Kennedy");
INSERT INTO Musicians (name) VALUES("Bridget (Fintan) Kenny");
INSERT INTO Musicians (name) VALUES("Jack Kenny");
INSERT INTO Musicians (name) VALUES("Lisa Kenny");
INSERT INTO Musicians (name) VALUES("Pat Kenny");
INSERT INTO Musicians (name) VALUES("Alex Kerr");
INSERT INTO Musicians (name) VALUES("Barry Kerr");
INSERT INTO Musicians (name) VALUES("Lucy Kerr");
INSERT INTO Musicians (name) VALUES("Jim Kerrigan");
INSERT INTO Musicians (name) VALUES("Breda Keville");
INSERT INTO Musicians (name) VALUES("Clare Keville");
INSERT INTO Musicians (name) VALUES("Daniel Kilfeather");
INSERT INTO Musicians (name) VALUES("Kilfenora Ceili Band");
INSERT INTO Musicians (name) VALUES("Jimmy Killeen");
INSERT INTO Musicians (name) VALUES("Paddy Killoran");
INSERT INTO Musicians (name) VALUES("Johnny Killourhy");
INSERT INTO Musicians (name) VALUES("Paddy Killourhy");
INSERT INTO Musicians (name) VALUES("Liz King");
INSERT INTO Musicians (name) VALUES("Michael King");
INSERT INTO Musicians (name) VALUES("Philip King");
INSERT INTO Musicians (name) VALUES("P.J King");
INSERT INTO Musicians (name) VALUES("David Kinsella");
INSERT INTO Musicians (name) VALUES("James Kinsella");
INSERT INTO Musicians (name) VALUES("Larry Kinsella");
INSERT INTO Musicians (name) VALUES("Mick Kinsella");
INSERT INTO Musicians (name) VALUES("Pádraig Kinsella");
INSERT INTO Musicians (name) VALUES("Brian Krause");
INSERT INTO Musicians (name) VALUES("Bridie Lafferty");
INSERT INTO Musicians (name) VALUES("Eugene Lambe");
INSERT INTO Musicians (name) VALUES("Chris Kitty Langan");
INSERT INTO Musicians (name) VALUES("Julia Langan");
INSERT INTO Musicians (name) VALUES("Brendan Larrissey");
INSERT INTO Musicians (name) VALUES("Brian Lavery");
INSERT INTO Musicians (name) VALUES("Mark Lavery");
INSERT INTO Musicians (name) VALUES("Fiona Lavin");
INSERT INTO Musicians (name) VALUES("Michael Lawlor");
INSERT INTO Musicians (name) VALUES("Ciara¡n Leahy");
INSERT INTO Musicians (name) VALUES("Tim Leahy");
INSERT INTO Musicians (name) VALUES("Ed Lee");
INSERT INTO Musicians (name) VALUES("Des Leech");
INSERT INTO Musicians (name) VALUES("Joe Leheny");
INSERT INTO Musicians (name) VALUES("Jennifer Lenihan");
INSERT INTO Musicians (name) VALUES("Tom Lenihan");
INSERT INTO Musicians (name) VALUES("Ben Lennon");
INSERT INTO Musicians (name) VALUES("Charlie Lennon");
INSERT INTO Musicians (name) VALUES("Maurice Lennon");
INSERT INTO Musicians (name) VALUES("John Leslie");
INSERT INTO Musicians (name) VALUES("Pat Leslie");
INSERT INTO Musicians (name) VALUES("Solen Lesouef");
INSERT INTO Musicians (name) VALUES("Liam Lewis");
INSERT INTO Musicians (name) VALUES("Bernadette Liddy");
INSERT INTO Musicians (name) VALUES("Denis Liddy");
INSERT INTO Musicians (name) VALUES("Joe Liddy");
INSERT INTO Musicians (name) VALUES("Mary Liddy");
INSERT INTO Musicians (name) VALUES("Tommy Liddy");
INSERT INTO Musicians (name) VALUES("Barry Limerick");
INSERT INTO Musicians (name) VALUES("Kitty");
INSERT INTO Musicians (name) VALUES("Tony Linnane");
INSERT INTO Musicians (name) VALUES("Meadhbh Ni Loclainn");
INSERT INTO Musicians (name) VALUES("Liam Mac Con Lomaire");
INSERT INTO Musicians (name) VALUES("Martin Long");
INSERT INTO Musicians (name) VALUES("Dr. Bill Loughnane");
INSERT INTO Musicians (name) VALUES("John Loughran");
INSERT INTO Musicians (name) VALUES("Lunasa");
INSERT INTO Musicians (name) VALUES("Donal Lunny");
INSERT INTO Musicians (name) VALUES("Cathal Lynch");
INSERT INTO Musicians (name) VALUES("John");
INSERT INTO Musicians (name) VALUES("Nonie Lynch");
INSERT INTO Musicians (name) VALUES("Pat");
INSERT INTO Musicians (name) VALUES("Patrick Lynch");
INSERT INTO Musicians (name) VALUES("Jimmy Lyons");
INSERT INTO Musicians (name) VALUES("Neill Lyons");
INSERT INTO Musicians (name) VALUES("Alphonsus Mac a’Bhaird");
INSERT INTO Musicians (name) VALUES("Columba Mac a’Bhaird");
INSERT INTO Musicians (name) VALUES("John na gCuinneagain Mac a’Bhaird");
INSERT INTO Musicians (name) VALUES("Seamus Mac a’Bhaird");
INSERT INTO Musicians (name) VALUES("Eogan Mac Eogain");
INSERT INTO Musicians (name) VALUES("Tomas Mac Aogain");
INSERT INTO Musicians (name) VALUES("Caoimhin Mac Aoidh");
INSERT INTO Musicians (name) VALUES("Colm Mac Confhaola");
INSERT INTO Musicians (name) VALUES("Pat Pheadar Mhick Mac Dabhait");
INSERT INTO Musicians (name) VALUES("Oisin");
INSERT INTO Musicians (name) VALUES("Mairtin Mac Donnacha");
INSERT INTO Musicians (name) VALUES("Peadar Mac Eli");
INSERT INTO Musicians (name) VALUES("Gearoid Mac Eogain");
INSERT INTO Musicians (name) VALUES("Ciaran Mac Feilimidh");
INSERT INTO Musicians (name) VALUES("Antoin Mac Gabhann");
INSERT INTO Musicians (name) VALUES("Dominic Mac Giolla Bhride");
INSERT INTO Musicians (name) VALUES("Ronan Mac Grianna");
INSERT INTO Musicians (name) VALUES("Seosamh Mac Grianna");
INSERT INTO Musicians (name) VALUES("Roddie Mac Isaac");
INSERT INTO Musicians (name) VALUES("Liam");
INSERT INTO Musicians (name) VALUES("Blind Fiddler Mac Lochlainn");
INSERT INTO Musicians (name) VALUES("Proinsias Mac Loscaigh");
INSERT INTO Musicians (name) VALUES("Tony Mac Mahon");
INSERT INTO Musicians (name) VALUES("Denis Mac Mahon");
INSERT INTO Musicians (name) VALUES("Ciaran Mac Mathuna");
INSERT INTO Musicians (name) VALUES("Lorcan Mac Mathuna");
INSERT INTO Musicians (name) VALUES("Andrew Mac Namara");
INSERT INTO Musicians (name) VALUES("Joe Mac Namara");
INSERT INTO Musicians (name) VALUES("Mary Mac Namara");
INSERT INTO Musicians (name) VALUES("Pat Mac Namara");
INSERT INTO Musicians (name) VALUES("Paddy Mac Namara");
INSERT INTO Musicians (name) VALUES("Sean Mac Namara");
INSERT INTO Musicians (name) VALUES("Paidraig Mac Suibhne");
INSERT INTO Musicians (name) VALUES("Nannie Rua Mac Sweeney");
INSERT INTO Musicians (name) VALUES("Turloch Mac Sweeney");
INSERT INTO Musicians (name) VALUES("Johnny Mc Afee");
INSERT INTO Musicians (name) VALUES("Johnny Mc Aleese");
INSERT INTO Musicians (name) VALUES("Sean Mc Aloon");
INSERT INTO Musicians (name) VALUES("Gabriel Mc Ardle");
INSERT INTO Musicians (name) VALUES("Collette Mc Aree");
INSERT INTO Musicians (name) VALUES("John Henry Mc Auley");
INSERT INTO Musicians (name) VALUES("Oisin Mc Auley");
INSERT INTO Musicians (name) VALUES("Cassie Mc Bride");
INSERT INTO Musicians (name) VALUES("Charlie Mc Bride");
INSERT INTO Musicians (name) VALUES("Jimmy Mc Bride");
INSERT INTO Musicians (name) VALUES("Willie Mc Bride");
INSERT INTO Musicians (name) VALUES("Sally Mc Bride");
INSERT INTO Musicians (name) VALUES("Andy Mc Cafferty");
INSERT INTO Musicians (name) VALUES("Julie Ann Mc Cafferty");
INSERT INTO Musicians (name) VALUES("Tom Mc Cafferty");
INSERT INTO Musicians (name) VALUES("Brenda Mc Cann");
INSERT INTO Musicians (name) VALUES("Charlie Mc Cahill");
INSERT INTO Musicians (name) VALUES("Pat Mc Cahill");
INSERT INTO Musicians (name) VALUES("Willie Mc Cahill");
INSERT INTO Musicians (name) VALUES("Conor Mc Carthy");
INSERT INTO Musicians (name) VALUES("Jamesie Mc Carthy");
INSERT INTO Musicians (name) VALUES("John Mc Carthy");
INSERT INTO Musicians (name) VALUES("Johnny Mc Carthy");
INSERT INTO Musicians (name) VALUES("May Mc Carthy");
INSERT INTO Musicians (name) VALUES("Seán Mc Carthy");
INSERT INTO Musicians (name) VALUES("Thomas Mc Carthy");
INSERT INTO Musicians (name) VALUES("Tommy Mc Carthy");
INSERT INTO Musicians (name) VALUES("Danny Mc Carry");
INSERT INTO Musicians (name) VALUES("Barney Mc Cauley");
INSERT INTO Musicians (name) VALUES("Niall Mc Clean");
INSERT INTO Musicians (name) VALUES("Dr. Malachy Mc Closkey");
INSERT INTO Musicians (name) VALUES("Stumpy Mc Closkey");
INSERT INTO Musicians (name) VALUES("Frank Mc Collam");
INSERT INTO Musicians (name) VALUES("Brian Mc Comb");
INSERT INTO Musicians (name) VALUES("Billy McComiskey");
INSERT INTO Musicians (name) VALUES("Mc Connells Four Leaf Shamrock Orchestra");
INSERT INTO Musicians (name) VALUES("Adam Mc Connell");
INSERT INTO Musicians (name) VALUES("Alec Mc Connell");
INSERT INTO Musicians (name) VALUES("Cathal Mc Connell");
INSERT INTO Musicians (name) VALUES("Jim Mc Connell");
INSERT INTO Musicians (name) VALUES("Mary Mc Connell");
INSERT INTO Musicians (name) VALUES("Mickey Mc Connell");
INSERT INTO Musicians (name) VALUES("Peter Mc Connell");
INSERT INTO Musicians (name) VALUES("Vincent Mc Connell");
INSERT INTO Musicians (name) VALUES("Anne Marie Mc Cormack");
INSERT INTO Musicians (name) VALUES("John Mc Cormack");
INSERT INTO Musicians (name) VALUES("John Mc Cormack");
INSERT INTO Musicians (name) VALUES("June Mc Cormack");
INSERT INTO Musicians (name) VALUES("Martin Mc Cormack");
INSERT INTO Musicians (name) VALUES("Billy Mc Cormick");
INSERT INTO Musicians (name) VALUES("Jack Mc Cutheon");
INSERT INTO Musicians (name) VALUES("Jimmy Mc Dade");
INSERT INTO Musicians (name) VALUES("Fred Mc Daid");
INSERT INTO Musicians (name) VALUES("Paddy Mc Daid");
INSERT INTO Musicians (name) VALUES("Ciara Mc Dermott");
INSERT INTO Musicians (name) VALUES("Elaine Mc Dermott");
INSERT INTO Musicians (name) VALUES("Josie Mc Dermott");
INSERT INTO Musicians (name) VALUES("Michael (Master) Mc Dermott");
INSERT INTO Musicians (name) VALUES("Pat Mc Dermott");
INSERT INTO Musicians (name) VALUES("Johnny Ringo Mc Donagh");
INSERT INTO Musicians (name) VALUES("Larry Mc Donagh");
INSERT INTO Musicians (name) VALUES("Michael Joe Mc Donagh");
INSERT INTO Musicians (name) VALUES("Paddy Mc Donagh");
INSERT INTO Musicians (name) VALUES("Patsy Mc Donagh");
INSERT INTO Musicians (name) VALUES("Sonny Mc Donagh");
INSERT INTO Musicians (name) VALUES("Randal Mc Donnell");
INSERT INTO Musicians (name) VALUES("Jack Mc Duff");
INSERT INTO Musicians (name) VALUES("Hugh Mc Dyer");
INSERT INTO Musicians (name) VALUES("Paddy ‘Pat’ Mc Dyer");
INSERT INTO Musicians (name) VALUES("Sean Mc Elwain");
INSERT INTO Musicians (name) VALUES("Paddy Mc Enespie");
INSERT INTO Musicians (name) VALUES("Patrick Mc Entee");
INSERT INTO Musicians (name) VALUES("Bill Mc Evoy");
INSERT INTO Musicians (name) VALUES("Catherine Mc Evoy");
INSERT INTO Musicians (name) VALUES("Conor Mc Evoy");
INSERT INTO Musicians (name) VALUES("John Mc Evoy");
INSERT INTO Musicians (name) VALUES("Mark Mc Evoy");
INSERT INTO Musicians (name) VALUES("Sarah Mc Evoy");
INSERT INTO Musicians (name) VALUES("Paddy (Bazzar) Mc Faddan");
INSERT INTO Musicians (name) VALUES("Frank Mc Fadden");
INSERT INTO Musicians (name) VALUES("Sam Mc Farlane");
INSERT INTO Musicians (name) VALUES("Andy Mc Gann");
INSERT INTO Musicians (name) VALUES("Mary Kate (Mc Gee) Mc Garrigle");
INSERT INTO Musicians (name) VALUES("Thomas Mc Garrigle");
INSERT INTO Musicians (name) VALUES("Felix Mc Garvey");
INSERT INTO Musicians (name) VALUES("George Mc Gee");
INSERT INTO Musicians (name) VALUES("Hughie Mc Gee");
INSERT INTO Musicians (name) VALUES("John Mc Gee");
INSERT INTO Musicians (name) VALUES("Mick Mc Gee");
INSERT INTO Musicians (name) VALUES("Pat");
INSERT INTO Musicians (name) VALUES("John Mc Gettigan");
INSERT INTO Musicians (name) VALUES("Jimmy Mc Gettrick");
INSERT INTO Musicians (name) VALUES("Brian Mc Gill");
INSERT INTO Musicians (name) VALUES("Colin Mc Gill");
INSERT INTO Musicians (name) VALUES("Jim Mc Gill");
INSERT INTO Musicians (name) VALUES("John");
INSERT INTO Musicians (name) VALUES("Willie Mc Gill");
INSERT INTO Musicians (name) VALUES("Andy Mc Ginley");
INSERT INTO Musicians (name) VALUES("Barney Mc Ginley");
INSERT INTO Musicians (name) VALUES("Con Mc Ginley");
INSERT INTO Musicians (name) VALUES("Condai Mc Ginley");
INSERT INTO Musicians (name) VALUES("Derek Mc Ginley");
INSERT INTO Musicians (name) VALUES("John Mc Ginley");
INSERT INTO Musicians (name) VALUES("John");
INSERT INTO Musicians (name) VALUES("Kathleen Mc Ginley");
INSERT INTO Musicians (name) VALUES("Martin Mc Ginley");
INSERT INTO Musicians (name) VALUES("Maurice (Mosie) Mc Ginley");
INSERT INTO Musicians (name) VALUES("Moses Mc Ginley");
INSERT INTO Musicians (name) VALUES("Nancy Mc Ginley");
INSERT INTO Musicians (name) VALUES("Padai (Mosie) Mc Ginley");
INSERT INTO Musicians (name) VALUES("Paddy Mc Ginley");
INSERT INTO Musicians (name) VALUES("Sean Mc Ginley");
INSERT INTO Musicians (name) VALUES("Eamon Mc Givney");
INSERT INTO Musicians (name) VALUES("Brendan Mc Glinchey");
INSERT INTO Musicians (name) VALUES("Paul Mc Glinchey");
INSERT INTO Musicians (name) VALUES("Arty Mc Glynn");
INSERT INTO Musicians (name) VALUES("Padai Bhartlai Mc Glynn");
INSERT INTO Musicians (name) VALUES("Alice Mc Goldrick");
INSERT INTO Musicians (name) VALUES("Laurence Mc Goldrick");
INSERT INTO Musicians (name) VALUES("Mick Mc Goldrick");
INSERT INTO Musicians (name) VALUES("Andy Mc Googan");
INSERT INTO Musicians (name) VALUES("Brian Mc Govern");
INSERT INTO Musicians (name) VALUES("Hugh Mc Govern");
INSERT INTO Musicians (name) VALUES("Daniel Mc Gowan");
INSERT INTO Musicians (name) VALUES("Harry Mc Gowan");
INSERT INTO Musicians (name) VALUES("Paddy Mc Gowan");
INSERT INTO Musicians (name) VALUES("Ted Mc Gowan");
INSERT INTO Musicians (name) VALUES("Hugo Mc Grath");
INSERT INTO Musicians (name) VALUES("Jim Mc Grath");
INSERT INTO Musicians (name) VALUES("John Mc Grath");
INSERT INTO Musicians (name) VALUES("Tom Pat Mc Grath");
INSERT INTO Musicians (name) VALUES("Vincent McGrath");
INSERT INTO Musicians (name) VALUES("Peg Needham (McGrath)");
INSERT INTO Musicians (name) VALUES("Paul Mc Grattan");
INSERT INTO Musicians (name) VALUES("Finbar Mc Greevy");
INSERT INTO Musicians (name) VALUES("Phil Mc Groarty");
INSERT INTO Musicians (name) VALUES("Ann Mc Groary");
INSERT INTO Musicians (name) VALUES("Ciaran Mc Guinness");
INSERT INTO Musicians (name) VALUES("Manus Mc Guire");
INSERT INTO Musicians (name) VALUES("Mary Mc Guire");
INSERT INTO Musicians (name) VALUES("Sean Mc Guire");
INSERT INTO Musicians (name) VALUES("Seamus Mc Guire");
INSERT INTO Musicians (name) VALUES("Jim Mc Gurk");
INSERT INTO Musicians (name) VALUES("Tom Mc Hale");
INSERT INTO Musicians (name) VALUES("Cassie Mc Henry");
INSERT INTO Musicians (name) VALUES("Brendan Mc Hugh");
INSERT INTO Musicians (name) VALUES("Francie Mc Hugh");
INSERT INTO Musicians (name) VALUES("Frank Mc Hugh");
INSERT INTO Musicians (name) VALUES("James Josie Mc Hugh");
INSERT INTO Musicians (name) VALUES("Jimmy Mc Hugh");
INSERT INTO Musicians (name) VALUES("Joseph Mc Hugh");
INSERT INTO Musicians (name) VALUES("Francis Mc Ilduff");
INSERT INTO Musicians (name) VALUES("Martin Mc Intyre");
INSERT INTO Musicians (name) VALUES("Terry Mc InTyre");
INSERT INTO Musicians (name) VALUES("Mike Mc Kee");
INSERT INTO Musicians (name) VALUES("Barney Mc Kenna");
INSERT INTO Musicians (name) VALUES("John Mc Kenna");
INSERT INTO Musicians (name) VALUES("Gay Mc Keon");
INSERT INTO Musicians (name) VALUES("Sean Mc Keon");
INSERT INTO Musicians (name) VALUES("John Mc Keown");
INSERT INTO Musicians (name) VALUES("Jim Mc Killop");
INSERT INTO Musicians (name) VALUES("Catherine (nee Nugent) McLaughlin");
INSERT INTO Musicians (name) VALUES("Dermot Mc Laughlin");
INSERT INTO Musicians (name) VALUES("Dinny Mc Laughlin");
INSERT INTO Musicians (name) VALUES("Edel Mc Laughlin");
INSERT INTO Musicians (name) VALUES("Finbar Mc Laughlin");
INSERT INTO Musicians (name) VALUES("Jimmie Mc Laughlin");
INSERT INTO Musicians (name) VALUES("Jimmy Mc Laughlin");
INSERT INTO Musicians (name) VALUES("John Mc Laughlin");
INSERT INTO Musicians (name) VALUES("John Dan Mc Laughlin");
INSERT INTO Musicians (name) VALUES("Donal Mc Mahon");
INSERT INTO Musicians (name) VALUES("James Mc Mahon");
INSERT INTO Musicians (name) VALUES("Fintan Mc Mahon");
INSERT INTO Musicians (name) VALUES("Tommy Mc Mahon");
INSERT INTO Musicians (name) VALUES("John Mc Manus");
INSERT INTO Musicians (name) VALUES("Pat Mc Manus");
INSERT INTO Musicians (name) VALUES("Joe Mc Menamin");
INSERT INTO Musicians (name) VALUES("Micheal McMenamen");
INSERT INTO Musicians (name) VALUES("Paddy Mc Menamin");
INSERT INTO Musicians (name) VALUES("Tommy Mc Menamin");
INSERT INTO Musicians (name) VALUES("Eddie Mc Monagle");
INSERT INTO Musicians (name) VALUES("Dominic Mc Nabb");
INSERT INTO Musicians (name) VALUES("Brian Mc Namara");
INSERT INTO Musicians (name) VALUES("Christy Mc Namara");
INSERT INTO Musicians (name) VALUES("Joe Mc Namara");
INSERT INTO Musicians (name) VALUES("Paddy Mc Namara");
INSERT INTO Musicians (name) VALUES("James Mc Namee");
INSERT INTO Musicians (name) VALUES("James Mc Neilis");
INSERT INTO Musicians (name) VALUES("John Mc Neilis");
INSERT INTO Musicians (name) VALUES("Frances Mc Peakes");
INSERT INTO Musicians (name) VALUES("Frank Mc Peakes");
INSERT INTO Musicians (name) VALUES("James Mc Peakes");
INSERT INTO Musicians (name) VALUES("Gerard Mc Quaid");
INSERT INTO Musicians (name) VALUES("Noreen Mc Quaid");
INSERT INTO Musicians (name) VALUES("Mick Mc Shane");
INSERT INTO Musicians (name) VALUES("John Mc Sherry");
INSERT INTO Musicians (name) VALUES("Bridget Della (Kelly) Mc Sweeney");
INSERT INTO Musicians (name) VALUES("Maurice Mc Sweeney");
INSERT INTO Musicians (name) VALUES("Kevin Mc Tiernan");
INSERT INTO Musicians (name) VALUES("Michael John Mc Tiernan");
INSERT INTO Musicians (name) VALUES("Peter Mackey");
INSERT INTO Musicians (name) VALUES("Joanie Madden");
INSERT INTO Musicians (name) VALUES("Joe Madden");
INSERT INTO Musicians (name) VALUES("Stephan Madden");
INSERT INTO Musicians (name) VALUES("Chris Maguire");
INSERT INTO Musicians (name) VALUES("Christopher Maguire");
INSERT INTO Musicians (name) VALUES("Cyril Maguire");
INSERT INTO Musicians (name) VALUES("Davy Maguire");
INSERT INTO Musicians (name) VALUES("Johnnie Maguire");
INSERT INTO Musicians (name) VALUES("Tommy Maguire");
INSERT INTO Musicians (name) VALUES("Sean Maguire");
INSERT INTO Musicians (name) VALUES("James Mahon");
INSERT INTO Musicians (name) VALUES("Jack Makem");
INSERT INTO Musicians (name) VALUES("Peter Makem");
INSERT INTO Musicians (name) VALUES("Sarah Makem");
INSERT INTO Musicians (name) VALUES("Tommy Makem");
INSERT INTO Musicians (name) VALUES("Bill");
INSERT INTO Musicians (name) VALUES("Pakie Malley");
INSERT INTO Musicians (name) VALUES("Annie");
INSERT INTO Musicians (name) VALUES("Marcus Maloney");
INSERT INTO Musicians (name) VALUES("Luke Maree");
INSERT INTO Musicians (name) VALUES("Elizabeth (Markham) Crotty");
INSERT INTO Musicians (name) VALUES("Maggie Markham");
INSERT INTO Musicians (name) VALUES("Andy Marley");
INSERT INTO Musicians (name) VALUES("Jimmy Marley");
INSERT INTO Musicians (name) VALUES("Kate Marquis");
INSERT INTO Musicians (name) VALUES("Josephine Marsh");
INSERT INTO Musicians (name) VALUES("Pat Marsh");
INSERT INTO Musicians (name) VALUES("Aedin Martin");
INSERT INTO Musicians (name) VALUES("Phil Philip Martin");
INSERT INTO Musicians (name) VALUES("Tommy Martin");
INSERT INTO Musicians (name) VALUES("Tony Martin");
INSERT INTO Musicians (name) VALUES("Emer Mayock");
INSERT INTO Musicians (name) VALUES("John Mayock");
INSERT INTO Musicians (name) VALUES("Ned Meagher");
INSERT INTO Musicians (name) VALUES("Charlie Meelan");
INSERT INTO Musicians (name) VALUES("Danny Meehan");
INSERT INTO Musicians (name) VALUES("Eddie Meehan");
INSERT INTO Musicians (name) VALUES("Edward Meehan");
INSERT INTO Musicians (name) VALUES("Jimmy Meehan");
INSERT INTO Musicians (name) VALUES("Jimmy Meehan");
INSERT INTO Musicians (name) VALUES("Kitty Meehan");
INSERT INTO Musicians (name) VALUES("Martin Meehan");
INSERT INTO Musicians (name) VALUES("Nan (Sheerin) Meehan");
INSERT INTO Musicians (name) VALUES("Paul Meehan");
INSERT INTO Musicians (name) VALUES("Peter Meehan");
INSERT INTO Musicians (name) VALUES("Seamus Meehan");
INSERT INTO Musicians (name) VALUES("Mel Mercier");
INSERT INTO Musicians (name) VALUES("Peadar Mercier");
INSERT INTO Musicians (name) VALUES("Mairead Ni Mhaonaigh");
INSERT INTO Musicians (name) VALUES("Mairead Mhic Dhonneha");
INSERT INTO Musicians (name) VALUES("Amelia Ni Mhurchu");
INSERT INTO Musicians (name) VALUES("Noreen Ni Mhurchu");
INSERT INTO Musicians (name) VALUES("Paddy Mills");
INSERT INTO Musicians (name) VALUES("Kevin Mitchell");
INSERT INTO Musicians (name) VALUES("Pat Mitchell");
INSERT INTO Musicians (name) VALUES("Johnnie (an Fidleir Beag) Molloy");
INSERT INTO Musicians (name) VALUES("Joe Molloy");
INSERT INTO Musicians (name) VALUES("Matt Molloy");
INSERT INTO Musicians (name) VALUES("Ryan Molloy");
INSERT INTO Musicians (name) VALUES("Ambrose Moloney");
INSERT INTO Musicians (name) VALUES("Andrew Moloney");
INSERT INTO Musicians (name) VALUES("Colette Moloney");
INSERT INTO Musicians (name) VALUES("Connie Moloney");
INSERT INTO Musicians (name) VALUES("Eddie Moloney");
INSERT INTO Musicians (name) VALUES("Jerry Moloney");
INSERT INTO Musicians (name) VALUES("John Moloney");
INSERT INTO Musicians (name) VALUES("Mick Moloney");
INSERT INTO Musicians (name) VALUES("Mick Moloney");
INSERT INTO Musicians (name) VALUES("Packie Moloney");
INSERT INTO Musicians (name) VALUES("Paddy Moloney");
INSERT INTO Musicians (name) VALUES("Pat \"Patsy\" Moloney");
INSERT INTO Musicians (name) VALUES("Sean Moloney");
INSERT INTO Musicians (name) VALUES("Stephan Moloney");
INSERT INTO Musicians (name) VALUES("Thomas Moloney");
INSERT INTO Musicians (name) VALUES("Eddie Monaghan");
INSERT INTO Musicians (name) VALUES("Francie Mooney");
INSERT INTO Musicians (name) VALUES("Christy Moore");
INSERT INTO Musicians (name) VALUES("Eddie Moore");
INSERT INTO Musicians (name) VALUES("Thomas Moore");
INSERT INTO Musicians (name) VALUES("Willie Moore");
INSERT INTO Musicians (name) VALUES("James Stoddard Moore");
INSERT INTO Musicians (name) VALUES("Jimmy O Brien Moran");
INSERT INTO Musicians (name) VALUES("Alex Morgan");
INSERT INTO Musicians (name) VALUES("Bob Morgan");
INSERT INTO Musicians (name) VALUES("Dan Morgan");
INSERT INTO Musicians (name) VALUES("Willie Morgan");
INSERT INTO Musicians (name) VALUES("Daniel Moroney");
INSERT INTO Musicians (name) VALUES("James Morrison");
INSERT INTO Musicians (name) VALUES("John Morrison");
INSERT INTO Musicians (name) VALUES("Tom Morrison");
INSERT INTO Musicians (name) VALUES("Tom Morrison");
INSERT INTO Musicians (name) VALUES("John Morrow");
INSERT INTO Musicians (name) VALUES("Thomas Morrow");
INSERT INTO Musicians (name) VALUES("John Moulden");
INSERT INTO Musicians (name) VALUES("Donnacha Moynihan");
INSERT INTO Musicians (name) VALUES("Jack Mulcaire");
INSERT INTO Musicians (name) VALUES("Louise Mulcahy");
INSERT INTO Musicians (name) VALUES("Michelle Mulcahy");
INSERT INTO Musicians (name) VALUES("Mick Mulcahy");
INSERT INTO Musicians (name) VALUES("Shane Mulchrone");
INSERT INTO Musicians (name) VALUES("James Mulcrone");
INSERT INTO Musicians (name) VALUES("Brendan Mulhair");
INSERT INTO Musicians (name) VALUES("Martin Mulhaire");
INSERT INTO Musicians (name) VALUES("Tommy Mulhaire");
INSERT INTO Musicians (name) VALUES("Pat Mulhearne");
INSERT INTO Musicians (name) VALUES("Eddie Mulhern");
INSERT INTO Musicians (name) VALUES("Katherine Mullally");
INSERT INTO Musicians (name) VALUES("William J. Mullaly");
INSERT INTO Musicians (name) VALUES("Damien Mullane");
INSERT INTO Musicians (name) VALUES("Edward Eddie Mullaney");
INSERT INTO Musicians (name) VALUES("Jimmy Mullen");
INSERT INTO Musicians (name) VALUES("Michael Mullins");
INSERT INTO Musicians (name) VALUES("Neillidh Mulligan");
INSERT INTO Musicians (name) VALUES("Willie Mulligan");
INSERT INTO Musicians (name) VALUES("Tom Mulligan");
INSERT INTO Musicians (name) VALUES("Paddy Mullins");
INSERT INTO Musicians (name) VALUES("Brendan Mulvihill");
INSERT INTO Musicians (name) VALUES("Brian Mulvihill");
INSERT INTO Musicians (name) VALUES("Bridgit (nee Flynn)");
INSERT INTO Musicians (name) VALUES("Charlie Mulvihill");
INSERT INTO Musicians (name) VALUES("Dawn");
INSERT INTO Musicians (name) VALUES("Gail");
INSERT INTO Musicians (name) VALUES("Martin Mulvihill");
INSERT INTO Musicians (name) VALUES("Anne Mulqueen");
INSERT INTO Musicians (name) VALUES("Tom Munnelly");
INSERT INTO Musicians (name) VALUES("Audrey Ni Murchu");
INSERT INTO Musicians (name) VALUES("Andrew Murphy");
INSERT INTO Musicians (name) VALUES("Colm Murphy");
INSERT INTO Musicians (name) VALUES("Cormac");
INSERT INTO Musicians (name) VALUES("Dan Murphy");
INSERT INTO Musicians (name) VALUES("Delia Murphy");
INSERT INTO Musicians (name) VALUES("Denis Murphy");
INSERT INTO Musicians (name) VALUES("Donal Murphy");
INSERT INTO Musicians (name) VALUES("Frank Murphy");
INSERT INTO Musicians (name) VALUES("Jack Murphy");
INSERT INTO Musicians (name) VALUES("James Murphy");
INSERT INTO Musicians (name) VALUES("John Boss Murphy");
INSERT INTO Musicians (name) VALUES("Liam Murphy");
INSERT INTO Musicians (name) VALUES("Mike Murphy");
INSERT INTO Musicians (name) VALUES("Paddy Murphy");
INSERT INTO Musicians (name) VALUES("Pat Murphy");
INSERT INTO Musicians (name) VALUES("Peter Murphy");
INSERT INTO Musicians (name) VALUES("Jimmy Murphy");
INSERT INTO Musicians (name) VALUES("John");
INSERT INTO Musicians (name) VALUES("Maggie Murphy (Chambers)");
INSERT INTO Musicians (name) VALUES("Phil Murphy");
INSERT INTO Musicians (name) VALUES("Philip Murphy");
INSERT INTO Musicians (name) VALUES("Pip Murphy");
INSERT INTO Musicians (name) VALUES("James Murray");
INSERT INTO Musicians (name) VALUES("Jim Murry");
INSERT INTO Musicians (name) VALUES("Martin Murray");
INSERT INTO Musicians (name) VALUES("Richard Murray");
INSERT INTO Musicians (name) VALUES("Sam Murray");
INSERT INTO Musicians (name) VALUES("Rose (nee Conlon) Murphy");
INSERT INTO Musicians (name) VALUES("Matt Naughton");
INSERT INTO Musicians (name) VALUES("Colin Nea");
INSERT INTO Musicians (name) VALUES("David Nealon");
INSERT INTO Musicians (name) VALUES("Richard Nealon");
INSERT INTO Musicians (name) VALUES("Eleanor (nee Kane) Neary");
INSERT INTO Musicians (name) VALUES("Jimmy Neary");
INSERT INTO Musicians (name) VALUES("Bronagh Needham");
INSERT INTO Musicians (name) VALUES("Peg Needham (McGrath)");
INSERT INTO Musicians (name) VALUES("Flaithri Neff");
INSERT INTO Musicians (name) VALUES("Johnny Neville");
INSERT INTO Musicians (name) VALUES("Niamh Ni Charra");
INSERT INTO Musicians (name) VALUES("Declan Noone");
INSERT INTO Musicians (name) VALUES("Jimmy Noonan");
INSERT INTO Musicians (name) VALUES("Aine Nugent");
INSERT INTO Musicians (name) VALUES("Catherine (nee Nugent) McLaughlin");
INSERT INTO Musicians (name) VALUES("Laurence Nugent");
INSERT INTO Musicians (name) VALUES("Marie (nee Nugent)");
INSERT INTO Musicians (name) VALUES("Packie Nugent");
INSERT INTO Musicians (name) VALUES("Sean Nugent");
INSERT INTO Musicians (name) VALUES("James (Lad)");
INSERT INTO Musicians (name) VALUES("Philip O’Beirne");
INSERT INTO Musicians (name) VALUES("Donncha O’Briain");
INSERT INTO Musicians (name) VALUES("Padraig O’Briain");
INSERT INTO Musicians (name) VALUES("Ann O’Brien");
INSERT INTO Musicians (name) VALUES("Caitríona O\'Brien");
INSERT INTO Musicians (name) VALUES("Dave O Brien");
INSERT INTO Musicians (name) VALUES("David O’Brien");
INSERT INTO Musicians (name) VALUES("David O’Brien");
INSERT INTO Musicians (name) VALUES("Dinny O’Brien");
INSERT INTO Musicians (name) VALUES("Eileen O Brien");
INSERT INTO Musicians (name) VALUES("Jimmy O Brien Moran");
INSERT INTO Musicians (name) VALUES("John O\' Brien");
INSERT INTO Musicians (name) VALUES("Lorainne O’Brien");
INSERT INTO Musicians (name) VALUES("Lorraine O Brien");
INSERT INTO Musicians (name) VALUES("Michael O\'Brien");
INSERT INTO Musicians (name) VALUES("Michelle O\'Brien");
INSERT INTO Musicians (name) VALUES("Mick O’Brien");
INSERT INTO Musicians (name) VALUES("Paddy O’Brien");
INSERT INTO Musicians (name) VALUES("Paddy O Brien");
INSERT INTO Musicians (name) VALUES("Pat O’Brien");
INSERT INTO Musicians (name) VALUES("Tom O’Brien");
INSERT INTO Musicians (name) VALUES("Mickey Ban O’Byrne");
INSERT INTO Musicians (name) VALUES("Francie Dearg O’Byrne");
INSERT INTO Musicians (name) VALUES("Pat O’Byrne");
INSERT INTO Musicians (name) VALUES("Geraldine O Callaghan");
INSERT INTO Musicians (name) VALUES("Tomas O’Canainn");
INSERT INTO Musicians (name) VALUES("Turlough O’Carolan");
INSERT INTO Musicians (name) VALUES("Maitiu O Cassaide");
INSERT INTO Musicians (name) VALUES("Darach O Cathain");
INSERT INTO Musicians (name) VALUES("Seán Ó Cathaláin");
INSERT INTO Musicians (name) VALUES("Tomas O Ceannabhain");
INSERT INTO Musicians (name) VALUES("Sean O’Cearbhaill");
INSERT INTO Musicians (name) VALUES("Aodan O\'Cheallaigh");
INSERT INTO Musicians (name) VALUES("Diarmuid O’Cionnaith");
INSERT INTO Musicians (name) VALUES("Padhraic O Cionnaith");
INSERT INTO Musicians (name) VALUES("Cathal Ó Clochasaigh");
INSERT INTO Musicians (name) VALUES("Padraig O Coill");
INSERT INTO Musicians (name) VALUES("Antóin O Conaill");
INSERT INTO Musicians (name) VALUES("Ciaran O Concannon");
INSERT INTO Musicians (name) VALUES("Aine O Connell");
INSERT INTO Musicians (name) VALUES("Connie O Connell");
INSERT INTO Musicians (name) VALUES("Michael O’Connell");
INSERT INTO Musicians (name) VALUES("Tom O\'Connell");
INSERT INTO Musicians (name) VALUES("Aine O Connor");
INSERT INTO Musicians (name) VALUES("Gerry O\'Connor");
INSERT INTO Musicians (name) VALUES("Gerry O\'Connor");
INSERT INTO Musicians (name) VALUES("Jim O’Connor");
INSERT INTO Musicians (name) VALUES("Liam O\'Connor");
INSERT INTO Musicians (name) VALUES("Mairtin O’Connor");
INSERT INTO Musicians (name) VALUES("Mick O’Connor");
INSERT INTO Musicians (name) VALUES("Pat O\'Connor");
INSERT INTO Musicians (name) VALUES("Rose O’Connor");
INSERT INTO Musicians (name) VALUES("Eanna O’Croinin");
INSERT INTO Musicians (name) VALUES("Nelius O’Cronin");
INSERT INTO Musicians (name) VALUES("Brian O Dea");
INSERT INTO Musicians (name) VALUES("Carmel O Dea");
INSERT INTO Musicians (name) VALUES("Aodh O Dhomhnaill");
INSERT INTO Musicians (name) VALUES("Conall O Dhomhnaill");
INSERT INTO Musicians (name) VALUES("Eamonn O’Doherty");
INSERT INTO Musicians (name) VALUES("Micheal O’Domhnaill");
INSERT INTO Musicians (name) VALUES("Aidan O\'Donnell");
INSERT INTO Musicians (name) VALUES("Brian O’Donnell");
INSERT INTO Musicians (name) VALUES("Colm O’Donnell");
INSERT INTO Musicians (name) VALUES("Danny O\'Donnell");
INSERT INTO Musicians (name) VALUES("P.V.O’Donnell");
INSERT INTO Musicians (name) VALUES("Cyril O’Donoghue");
INSERT INTO Musicians (name) VALUES("Jimmy O’Donoghue");
INSERT INTO Musicians (name) VALUES("Paddy O’Donoghue");
INSERT INTO Musicians (name) VALUES("Dan O Dowd");
INSERT INTO Musicians (name) VALUES("Joe O’Dowd");
INSERT INTO Musicians (name) VALUES("Seamie O’Dowd");
INSERT INTO Musicians (name) VALUES("Sheila (nee Regan) O’Dowd");
INSERT INTO Musicians (name) VALUES("Paul O’Driscoll");
INSERT INTO Musicians (name) VALUES("Sean O Driscoll");
INSERT INTO Musicians (name) VALUES("Tiarnan O\'Duinchinn");
INSERT INTO Musicians (name) VALUES("Sean O Dulaing");
INSERT INTO Musicians (name) VALUES("Antaine O Farachain");
INSERT INTO Musicians (name) VALUES("Liam O Flynn");
INSERT INTO Musicians (name) VALUES("Paddy O’Gara");
INSERT INTO Musicians (name) VALUES("Paddy O’Gara");
INSERT INTO Musicians (name) VALUES("Brid O Gorman");
INSERT INTO Musicians (name) VALUES("Ned O’Gorman");
INSERT INTO Musicians (name) VALUES("Conal O’Grada");
INSERT INTO Musicians (name) VALUES("Patsy O\'Grady");
INSERT INTO Musicians (name) VALUES("Gearoid O hAllmhurain");
INSERT INTO Musicians (name) VALUES("Michea¡l O Halmhain");
INSERT INTO Musicians (name) VALUES("Thomas O’Hannigan");
INSERT INTO Musicians (name) VALUES("Meabh O\'Hare");
INSERT INTO Musicians (name) VALUES("Walter O\'Hara");
INSERT INTO Musicians (name) VALUES("Michael Ó hEineachain");
INSERT INTO Musicians (name) VALUES("Frank O’Higgins");
INSERT INTO Musicians (name) VALUES("Shane O’hUaithne");
INSERT INTO Musicians (name) VALUES("Maire O’Keeffe");
INSERT INTO Musicians (name) VALUES("Maurice O\'Keefe");
INSERT INTO Musicians (name) VALUES("Padraig O\'Keeffe");
INSERT INTO Musicians (name) VALUES("Donnehadha O’Laoghaire");
INSERT INTO Musicians (name) VALUES("Collette O\'Leary");
INSERT INTO Musicians (name) VALUES("Johnny O Leary");
INSERT INTO Musicians (name) VALUES("Sharon O Leary");
INSERT INTO Musicians (name) VALUES("Dan O’Loan");
INSERT INTO Musicians (name) VALUES("Peadar O\'Loughlin");
INSERT INTO Musicians (name) VALUES("Tomas O’Maclain");
INSERT INTO Musicians (name) VALUES("Martin O Malley");
INSERT INTO Musicians (name) VALUES("Ciaran O Maonaigh");
INSERT INTO Musicians (name) VALUES("Gearoid O Maonaigh");
INSERT INTO Musicians (name) VALUES("Richard Lewis O’Mealy");
INSERT INTO Musicians (name) VALUES("Fiachra Ó Mongain");
INSERT INTO Musicians (name) VALUES("Séamus Ó Mongáin");
INSERT INTO Musicians (name) VALUES("Donal O’Morain");
INSERT INTO Musicians (name) VALUES("Padraig O\'Muineachain");
INSERT INTO Musicians (name) VALUES("Andreas O Murchu");
INSERT INTO Musicians (name) VALUES("Eamonn O’ Murchu");
INSERT INTO Musicians (name) VALUES("Marcus O Murchu");
INSERT INTO Musicians (name) VALUES("Sean O’Murchu");
INSERT INTO Musicians (name) VALUES("Aidan O’Neill");
INSERT INTO Musicians (name) VALUES("Arthur O’Neill");
INSERT INTO Musicians (name) VALUES("Charlie O’Neill");
INSERT INTO Musicians (name) VALUES("Eoin O Neill");
INSERT INTO Musicians (name) VALUES("Francis (Captain) O’Neill");
INSERT INTO Musicians (name) VALUES("James O’Neill");
INSERT INTO Musicians (name) VALUES("Pat O’Neill");
INSERT INTO Musicians (name) VALUES("Sean O’Neill");
INSERT INTO Musicians (name) VALUES("Shaun O’Nolan");
INSERT INTO Musicians (name) VALUES("Caoimhin O Raghallaigh");
INSERT INTO Musicians (name) VALUES("Micheal O\'Raghallaigh");
INSERT INTO Musicians (name) VALUES("Catherine ( Glackin) O\'Reilly");
INSERT INTO Musicians (name) VALUES("M.J. O\' Reilly");
INSERT INTO Musicians (name) VALUES("Micheal O’Riabhaigh");
INSERT INTO Musicians (name) VALUES("Sean O Riada");
INSERT INTO Musicians (name) VALUES("Fiachra O’ Riagain");
INSERT INTO Musicians (name) VALUES("Edward O Rourke");
INSERT INTO Musicians (name) VALUES("Michael O Rourke");
INSERT INTO Musicians (name) VALUES("Jimmi O’Se");
INSERT INTO Musicians (name) VALUES("Sean O’Se");
INSERT INTO Musicians (name) VALUES("Brother Gildas O\'Shea");
INSERT INTO Musicians (name) VALUES("John Jack O’Shaughnessy");
INSERT INTO Musicians (name) VALUES("Paul O\'Shaughnessy");
INSERT INTO Musicians (name) VALUES("Pearl O’Shaughnessy");
INSERT INTO Musicians (name) VALUES("Tom O’Shaughnessy");
INSERT INTO Musicians (name) VALUES("Eoghan Rua O’Suilleabhain");
INSERT INTO Musicians (name) VALUES("Micheal O’Suilleabhain");
INSERT INTO Musicians (name) VALUES("Bernard O’Sullivan");
INSERT INTO Musicians (name) VALUES("Dymphna O\'Sullivan");
INSERT INTO Musicians (name) VALUES("Jerry O’Sullivan");
INSERT INTO Musicians (name) VALUES("John O\'Sullivan");
INSERT INTO Musicians (name) VALUES("Michelle O’Sullivan");
INSERT INTO Musicians (name) VALUES("Paddy O’Sullivan");
INSERT INTO Musicians (name) VALUES("Tomas O Tuathail");
INSERT INTO Musicians (name) VALUES("Holly Nic Oireachtaigh");
INSERT INTO Musicians (name) VALUES("Peter Oliver");
INSERT INTO Musicians (name) VALUES("Annette Owens");
INSERT INTO Musicians (name) VALUES("Bryan Palmer");
INSERT INTO Musicians (name) VALUES("Charlie Patton");
INSERT INTO Musicians (name) VALUES("Mary Anne (nee Mc Phelimy) Patton");
INSERT INTO Musicians (name) VALUES("Christina Pearse");
INSERT INTO Musicians (name) VALUES("John Pedersen");
INSERT INTO Musicians (name) VALUES("Bob Peoples");
INSERT INTO Musicians (name) VALUES("George Peoples");
INSERT INTO Musicians (name) VALUES("Jimmy (Jamie) Peoples");
INSERT INTO Musicians (name) VALUES("Matt (Mattha) Peoples");
INSERT INTO Musicians (name) VALUES("Siobhan Peoples");
INSERT INTO Musicians (name) VALUES("Tom Peoples");
INSERT INTO Musicians (name) VALUES("Tommy Peoples");
INSERT INTO Musicians (name) VALUES("George Petrie");
INSERT INTO Musicians (name) VALUES("Conal Eoghain Phadraig");
INSERT INTO Musicians (name) VALUES("Jim Phat");
INSERT INTO Musicians (name) VALUES("Jason Philbin");
INSERT INTO Musicians (name) VALUES("Ashling Phillips");
INSERT INTO Musicians (name) VALUES("Paul Phillips");
INSERT INTO Musicians (name) VALUES("Charlie Piggott");
INSERT INTO Musicians (name) VALUES("John Edward Pigot");
INSERT INTO Musicians (name) VALUES("Planxty");
INSERT INTO Musicians (name) VALUES("John Ponsonby");
INSERT INTO Musicians (name) VALUES("Sarah (Mc Ginty) Ponsonby");
INSERT INTO Musicians (name) VALUES("John Potts");
INSERT INTO Musicians (name) VALUES("Sean Potts");
INSERT INTO Musicians (name) VALUES("Tommy Potts");
INSERT INTO Musicians (name) VALUES("David Power");
INSERT INTO Musicians (name) VALUES("Jimmy Power");
INSERT INTO Musicians (name) VALUES("John Power");
INSERT INTO Musicians (name) VALUES("Martin Preshaw");
INSERT INTO Musicians (name) VALUES("David Preston");
INSERT INTO Musicians (name) VALUES("Eugene Preston");
INSERT INTO Musicians (name) VALUES("Louis Preston");
INSERT INTO Musicians (name) VALUES("Michael Preston");
INSERT INTO Musicians (name) VALUES("Maria Shannon Preston");
INSERT INTO Musicians (name) VALUES("Viola Preston");
INSERT INTO Musicians (name) VALUES("John Queally");
INSERT INTO Musicians (name) VALUES("Michael Queally");
INSERT INTO Musicians (name) VALUES("PaddyQueally");
INSERT INTO Musicians (name) VALUES("Paddy ‘Ban’ Guigley");
INSERT INTO Musicians (name) VALUES("Aine Quigney");
INSERT INTO Musicians (name) VALUES("Anthony Quigney");
INSERT INTO Musicians (name) VALUES("Marie Quigney");
INSERT INTO Musicians (name) VALUES("Cormac Quinn");
INSERT INTO Musicians (name) VALUES("Francy Quinn");
INSERT INTO Musicians (name) VALUES("Frank Quinn");
INSERT INTO Musicians (name) VALUES("Louis E. Quinn");
INSERT INTO Musicians (name) VALUES("Sean Quinn");
INSERT INTO Musicians (name) VALUES("Murty Rabbett");
INSERT INTO Musicians (name) VALUES("Anna Rafferty");
INSERT INTO Musicians (name) VALUES("Kathleen “Moloney” Rafferty");
INSERT INTO Musicians (name) VALUES("Mary Rafferty");
INSERT INTO Musicians (name) VALUES("Mike Rafferty");
INSERT INTO Musicians (name) VALUES("Paddy Rafferty");
INSERT INTO Musicians (name) VALUES("Thomas “Barrel” Rafferty");
INSERT INTO Musicians (name) VALUES("Tommy Rafferty");
INSERT INTO Musicians (name) VALUES("Biddy Rainey");
INSERT INTO Musicians (name) VALUES("Paddy Rainey");
INSERT INTO Musicians (name) VALUES("Stephen Rainey");
INSERT INTO Musicians (name) VALUES("John Rea");
INSERT INTO Musicians (name) VALUES("Ed");
INSERT INTO Musicians (name) VALUES("Tommy Reck");
INSERT INTO Musicians (name) VALUES("Larry Redican");
INSERT INTO Musicians (name) VALUES("Janine Redmond");
INSERT INTO Musicians (name) VALUES("Elizabeth (nee Regan) Kielty");
INSERT INTO Musicians (name) VALUES("Frank Regan Snr.");
INSERT INTO Musicians (name) VALUES("Frank Regan Jnr.");
INSERT INTO Musicians (name) VALUES("Mick Regan");
INSERT INTO Musicians (name) VALUES("Tom Regan");
INSERT INTO Musicians (name) VALUES("Sheila (nee Regan) O’Dowd");
INSERT INTO Musicians (name) VALUES("Loretto Reid");
INSERT INTO Musicians (name) VALUES("Sean Reid");
INSERT INTO Musicians (name) VALUES("Martin Reidy");
INSERT INTO Musicians (name) VALUES("John Reilly");
INSERT INTO Musicians (name) VALUES("Jack Reynolds");
INSERT INTO Musicians (name) VALUES("Larry Reynolds Sr.");
INSERT INTO Musicians (name) VALUES("Paddy Reynolds");
INSERT INTO Musicians (name) VALUES("Willie Reynolds");
INSERT INTO Musicians (name) VALUES("Áine Sinead Ní Riain");
INSERT INTO Musicians (name) VALUES("Noel Rice");
INSERT INTO Musicians (name) VALUES("Liam Roberts");
INSERT INTO Musicians (name) VALUES("Mark Roberts");
INSERT INTO Musicians (name) VALUES("Brian Roche");
INSERT INTO Musicians (name) VALUES("David (Davey) Roche");
INSERT INTO Musicians (name) VALUES("Frank Roche");
INSERT INTO Musicians (name) VALUES("Jonathan Roche");
INSERT INTO Musicians (name) VALUES("Pat Roche");
INSERT INTO Musicians (name) VALUES("Martin Rochford");
INSERT INTO Musicians (name) VALUES("Andreas Rogge");
INSERT INTO Musicians (name) VALUES("Michael Rooney");
INSERT INTO Musicians (name) VALUES("Tristan Rosenstock");
INSERT INTO Musicians (name) VALUES("George Ross");
INSERT INTO Musicians (name) VALUES("John Rourke");
INSERT INTO Musicians (name) VALUES("Helena Rowsome");
INSERT INTO Musicians (name) VALUES("John Rowsome");
INSERT INTO Musicians (name) VALUES("Kevin Rowsome");
INSERT INTO Musicians (name) VALUES("Leo Rowsome");
INSERT INTO Musicians (name) VALUES("Leon Rowsome");
INSERT INTO Musicians (name) VALUES("Liam Rowsome");
INSERT INTO Musicians (name) VALUES("Lorraine Hickey Rowsome");
INSERT INTO Musicians (name) VALUES("Noirin (Ni Flaitheartaigh) Rowsome");
INSERT INTO Musicians (name) VALUES("Olivia Rowsome");
INSERT INTO Musicians (name) VALUES("Thomas Rowsome");
INSERT INTO Musicians (name) VALUES("Tom Rowsome");
INSERT INTO Musicians (name) VALUES("Samuel Rowsome");
INSERT INTO Musicians (name) VALUES("Samual Jr");
INSERT INTO Musicians (name) VALUES("William Rowsome");
INSERT INTO Musicians (name) VALUES("Fionnuala Ni Ruanaidh");
INSERT INTO Musicians (name) VALUES("Thomas Rudd");
INSERT INTO Musicians (name) VALUES("Dominic Rushe");
INSERT INTO Musicians (name) VALUES("Hugh Rushie");
INSERT INTO Musicians (name) VALUES("Austin Russell");
INSERT INTO Musicians (name) VALUES("Austin Rua Russell");
INSERT INTO Musicians (name) VALUES("Annie (Maloney) Russell");
INSERT INTO Musicians (name) VALUES("Gussie Russell");
INSERT INTO Musicians (name) VALUES("Micho Russell");
INSERT INTO Musicians (name) VALUES("Packie Russell");
INSERT INTO Musicians (name) VALUES("Joe Ryan");
INSERT INTO Musicians (name) VALUES("Murty (Martin) Ryan");
INSERT INTO Musicians (name) VALUES("Noel Ryan");
INSERT INTO Musicians (name) VALUES("Paddy Ryan");
INSERT INTO Musicians (name) VALUES("Sean Ryan");
INSERT INTO Musicians (name) VALUES("Sean Ryan");
INSERT INTO Musicians (name) VALUES("Thomas Ryan");
INSERT INTO Musicians (name) VALUES("Anne Rynne");
INSERT INTO Musicians (name) VALUES("John Rynne");
INSERT INTO Musicians (name) VALUES("Padraig Rynne");
INSERT INTO Musicians (name) VALUES("Naisrin El Safti");
INSERT INTO Musicians (name) VALUES("K. Scanlon");
INSERT INTO Musicians (name) VALUES("Sile Ni Scannlain");
INSERT INTO Musicians (name) VALUES("Bruce Scott");
INSERT INTO Musicians (name) VALUES("Jim Seery");
INSERT INTO Musicians (name) VALUES("Sean Seery");
INSERT INTO Musicians (name) VALUES("Aaron Setunsky");
INSERT INTO Musicians (name) VALUES("Aidan Shannon");
INSERT INTO Musicians (name) VALUES("Breda Shannon");
INSERT INTO Musicians (name) VALUES("Garry Shannon");
INSERT INTO Musicians (name) VALUES("Joe Shannon");
INSERT INTO Musicians (name) VALUES("Mick Shannon");
INSERT INTO Musicians (name) VALUES("Packie Shannon");
INSERT INTO Musicians (name) VALUES("Paddy Shannon");
INSERT INTO Musicians (name) VALUES("Seamus Shannon");
INSERT INTO Musicians (name) VALUES("Sharon Shannon");
INSERT INTO Musicians (name) VALUES("Shaskeen");
INSERT INTO Musicians (name) VALUES("David");
INSERT INTO Musicians (name) VALUES("Josie");
INSERT INTO Musicians (name) VALUES("Michael");
INSERT INTO Musicians (name) VALUES("Michael");
INSERT INTO Musicians (name) VALUES("Roger Sherlock");
INSERT INTO Musicians (name) VALUES("John Skelton");
INSERT INTO Musicians (name) VALUES("John Slevin");
INSERT INTO Musicians (name) VALUES("Peter Smith");
INSERT INTO Musicians (name) VALUES("Breda Smyth");
INSERT INTO Musicians (name) VALUES("Mikie Smyth");
INSERT INTO Musicians (name) VALUES("Seán Smyth");
INSERT INTO Musicians (name) VALUES("Davy Spillane");
INSERT INTO Musicians (name) VALUES("Daithi Sproule");
INSERT INTO Musicians (name) VALUES("Patrick Stack");
INSERT INTO Musicians (name) VALUES("Brian Stafford");
INSERT INTO Musicians (name) VALUES("Charles Villiers Stanford");
INSERT INTO Musicians (name) VALUES("Kathleen Staunton");
INSERT INTO Musicians (name) VALUES("Mary Staunton");
INSERT INTO Musicians (name) VALUES("Mattie Staunton");
INSERT INTO Musicians (name) VALUES("Nora Staunton");
INSERT INTO Musicians (name) VALUES("Damien Stenson");
INSERT INTO Musicians (name) VALUES("Gary Stenson");
INSERT INTO Musicians (name) VALUES("Joe Stenson");
INSERT INTO Musicians (name) VALUES("Sam Stevenson");
INSERT INTO Musicians (name) VALUES("Rosie Stewart");
INSERT INTO Musicians (name) VALUES("Trevor Stewart");
INSERT INTO Musicians (name) VALUES("Tommy Stone");
INSERT INTO Musicians (name) VALUES("Dan Sullivan");
INSERT INTO Musicians (name) VALUES("Dan Sullivan");
INSERT INTO Musicians (name) VALUES("Brenda Sweeney");
INSERT INTO Musicians (name) VALUES("Kate Sweeney");
INSERT INTO Musicians (name) VALUES("Noel Sweeney");
INSERT INTO Musicians (name) VALUES("Seamus Sweeney");
INSERT INTO Musicians (name) VALUES("Paddy Sweeney");
INSERT INTO Musicians (name) VALUES("William Talbot");
INSERT INTO Musicians (name) VALUES("Martin Talty");
INSERT INTO Musicians (name) VALUES("Seamus Tansey");
INSERT INTO Musicians (name) VALUES("Din Tarrant");
INSERT INTO Musicians (name) VALUES("Billy Taylor");
INSERT INTO Musicians (name) VALUES("Mike Taylor");
INSERT INTO Musicians (name) VALUES("Mortimer Taylor");
INSERT INTO Musicians (name) VALUES("Paddy Taylor");
INSERT INTO Musicians (name) VALUES("Teada");
INSERT INTO Musicians (name) VALUES("Terry Teahan");
INSERT INTO Musicians (name) VALUES("Oliver Thomas");
INSERT INTO Musicians (name) VALUES("Alan Tierney");
INSERT INTO Musicians (name) VALUES("John Tierney");
INSERT INTO Musicians (name) VALUES("Myles Tinney");
INSERT INTO Musicians (name) VALUES("Patrick J. (Patsy) Touhey");
INSERT INTO Musicians (name) VALUES("Pat Towey");
INSERT INTO Musicians (name) VALUES("Peter");
INSERT INTO Musicians (name) VALUES("Peter Tracey");
INSERT INTO Musicians (name) VALUES("Hughie Travers");
INSERT INTO Musicians (name) VALUES("John Travers");
INSERT INTO Musicians (name) VALUES("Patrick Travers");
INSERT INTO Musicians (name) VALUES("Rena Traynor");
INSERT INTO Musicians (name) VALUES("Tom Traynor");
INSERT INTO Musicians (name) VALUES("Paddy Treacy");
INSERT INTO Musicians (name) VALUES("Ciaran Tourish");
INSERT INTO Musicians (name) VALUES("Martin Tourish");
INSERT INTO Musicians (name) VALUES("Michael Tubridy");
INSERT INTO Musicians (name) VALUES("Tulla Ceili Band");
INSERT INTO Musicians (name) VALUES("Conor Tully");
INSERT INTO Musicians (name) VALUES("Ned Turbit");
INSERT INTO Musicians (name) VALUES("Peter Turbit");
INSERT INTO Musicians (name) VALUES("John Joe Tuttle");
INSERT INTO Musicians (name) VALUES("Aoife Ni Uaithne");
INSERT INTO Musicians (name) VALUES("Eimear Ni Uallaigh");
INSERT INTO Musicians (name) VALUES("Brian Vallely");
INSERT INTO Musicians (name) VALUES("Caoimhin Vallely");
INSERT INTO Musicians (name) VALUES("Cillian Vallely");
INSERT INTO Musicians (name) VALUES("Eithne Vallely");
INSERT INTO Musicians (name) VALUES("Fintan Vallely");
INSERT INTO Musicians (name) VALUES("Niall Vallely");
INSERT INTO Musicians (name) VALUES("Aidan Vaughan");
INSERT INTO Musicians (name) VALUES("John Francis Vesey");
INSERT INTO Musicians (name) VALUES("Eamonn Walsh");
INSERT INTO Musicians (name) VALUES("Emer Walsh");
INSERT INTO Musicians (name) VALUES("Garry Walsh");
INSERT INTO Musicians (name) VALUES("Ina Walsh");
INSERT INTO Musicians (name) VALUES("John Walsh");
INSERT INTO Musicians (name) VALUES("Liam Walsh");
INSERT INTO Musicians (name) VALUES("Michael Walsh");
INSERT INTO Musicians (name) VALUES("Tommy Walsh");
INSERT INTO Musicians (name) VALUES("Tony Walsh");
INSERT INTO Musicians (name) VALUES("Jack Wade");
INSERT INTO Musicians (name) VALUES("James Ward");
INSERT INTO Musicians (name) VALUES("John Ward");
INSERT INTO Musicians (name) VALUES("Pat Ward");
INSERT INTO Musicians (name) VALUES("Dean Warner");
INSERT INTO Musicians (name) VALUES("Glen Watson");
INSERT INTO Musicians (name) VALUES("Con Watters");
INSERT INTO Musicians (name) VALUES("Connell Watters");
INSERT INTO Musicians (name) VALUES("John Watters");
INSERT INTO Musicians (name) VALUES("John Weir");
INSERT INTO Musicians (name) VALUES("Willie Weir");
INSERT INTO Musicians (name) VALUES("Gavin Whelan");
INSERT INTO Musicians (name) VALUES("George Whelan");
INSERT INTO Musicians (name) VALUES("Joe Whelan");
INSERT INTO Musicians (name) VALUES("Tommy Whelan");
INSERT INTO Musicians (name) VALUES("Aggie White");
INSERT INTO Musicians (name) VALUES("Roisin White");
INSERT INTO Musicians (name) VALUES("Sean White");
INSERT INTO Musicians (name) VALUES("Kevin Whitty");
INSERT INTO Musicians (name) VALUES("Tommy Whyte");
INSERT INTO Musicians (name) VALUES("Dan Wilkinson");
INSERT INTO Musicians (name) VALUES("Charlie Woods");
INSERT INTO Musicians (name) VALUES("Sarah-Jane Woods");
INSERT INTO Musicians (name) VALUES("Mairead Wright");
INSERT INTO Musicians (name) VALUES("Patricia Wright");
INSERT INTO Musicians (name) VALUES("Joe Wyer");
INSERT INTO Musicians (name) VALUES("Liz Wynne");
INSERT INTO Musicians (name) VALUES("Martin Wynne");
INSERT INTO Musicians (name) VALUES("John Wynne");
